- linodecli/resources/linode.py
Prevents the API from getting bad values.
> linode: specify a default for stackscriptjson

- linodecli/resources/linode.py
similar to this commit:
https://github.com/linode/linode-cli/commit/26a4801a5cd4713912656f5ff781c58e95d8a948
there was an extra boot command that was causing the 400 error.
pre-edit:
~/github/linode-cli -> linode-cli rebuild rebuild-test
Root Password:
Error: 400: Linode busy.;
~/github/linode-cli ->
post-edit:
~/github/linode-cli -> linode-cli rebuild rebuild-test
Root Password:
~/github/linode-cli ->
> fix '400/linode busy' on rebuild

- README.rst
- linodecli/cli.py
- linodecli/operation.py
Typing passwords on the command line is no good, so now passwords may be
entered through a password prompt if desired.  If you're automating the
creation of Linodes of other actions that require passwords, you may
still specify the password on the command line as you used to.
> Added support for secure password input

- Makefile
I really like what @ginkgomzd with the build process - I'm not going to
lie, this is my first Makefile, and I appreciate the cleanup.  I had a
few ideas looking it over:
If we're going to build a package during the install process,
why not install the package that we just built?  I think that works
better anyway - once you test the package that was installed, you can
confidently distribute it knowing that it is the same code you just ran.
I also  added a clean step to delete all of the generated files
(linodecli/data-* and linode-cli.sh along with the contents of dist/) to
make sure everything's fresh with each build.
> Couple of ideas to further improve the builder

- linodecli/__init__.py
Without this, a malicious API spec YAML file could execute arbitrary code as the user
> Use yaml.safe_load() instead of yaml.load()

- .dockerignore
- Dockerfile-bats
- README.rst
* Adds Dockerfile to run BATS tests
* Adds dockerignore file so that builds/dist files are ignored when creating the docker image
* This PR was based off the domains test branch, I will rebase once that PR is merged. The main files of concern here are `Dockerfile-bats` `.dockerignore` and `README.rst`
***Please remember these TESTS **WILL DELETE ALL RESOURCES** (linodes/volumes/domains/nodebalancers/etc/etc) associated with your linode account!***
* Follow the instructions for running via docker in the README
cc. @Dorthu
> BATS tests Dockerfile

- Dockerfile-bats
* Allows overriding the api url provided by the `openapi.yaml` file. This will allow running the bats tests on non-default environments
* This does assume a default api url in the openapi spec of `https://api.linode.com/v4`.. @Dorthu  we can change this to be dynamic and call it `ORIGINAL_API_ROUTE` or something like it, should we need to make this more robust.
```bash
docker build -f Dockerfile-bats -t linode-cli --no-cache --build-arg SPEC="https://some-custom-path.com/openapi.yaml" --build-arg TOKEN=ENTER-YOUR-TOKEN-HERE --build-arg API_OVERRIDE="some-custom-path.myAPI.com" .
docker run --rm linode-cli
```
> Testing - API Base Url Override

- test/common.bash
- test/test-runner.sh
- test/volumes/attach-detach-volumes.bats
- test/volumes/create-volumes.bats
- test/volumes/list-view-update-volumes.bats
- test/volumes/resize-volumes.bats
* Added BATS tests for volumes
* Disabled tests for attaching/detaching volumes because they seem to be problematic due to ARB-763. 
* Ensure your `~/.linode-cli` config uses a test user token, running the tests removes all resources associated with the test account. YOU HAVE BEEN WARNED.
* From the base of the repo:
```bash
./test/test-runner.sh
```
> Volumes BATS tests

- linodecli/configuration.py
I added a check to see if `configure()` has already been called in the execution run. This prevents it from running twice if `linode-cli configure` ever happens to be the very first command ran with the CLI.
Cheers,
> fix(#53): linodecli configure no longer configures twice on first run

- linodecli/cli.py
Does exactly as the PR says.
If there are more warnings that this flag should suppress, it should be a matter of adding a check for `self.suppress_warnings` before the warnings are output.
If you provide me with a list of such code locations or strings, I can quickly add them to this PR.
Cheers,
> feat(#51): Added `--suppress-warnings` flag to ignore newer API versions

- .gitignore
- linodecli/configuration.py
Following the discussion in #52, I've made this pull request which adds basic support for a `LINODE_TOKEN` environment variable which stores the OAuth token.
This is rudimentary and will break support for multiple profiles (only when using LINODE_TOKEN), although it's technically feasible with a pattern like `LINODE_<USER>_TOKEN` which can be supported quite easily. (I've added a warning to `configure` if LINODE_TOKEN is detected.)
I'm not too sure how I feel about sensitive data in environment variables, but given that this is how a lot of cloud providers do it, and given that this most likely runs on single user systems, I think it should be fairly safe.
If you feel like it's needed, I can quickly add the multiple profile support for environment variables.
I'm also considering adding …
> feat: Support access token in LINODE_TOKEN environment variable.

- Dockerfile-bats
- test/test-runner.sh
- test/volumes/list-view-update-volumes.bats
* Adds the volumes tests directory to the BATS dockerfile start command 
* Updates the test runner to look for `.bats` files in the test directory
* updates the assertion for the list volumes test to accept `creating` or `active` response from the API, because volume creation is quick! apparently.
> Add Volumes tests to test Dockerfile command

- Dockerfile-bats
- Makefile
- README.rst
This changed upstream, so it needed to be updated.  Builds without this
change will fail.
> Updated URL to public OpenAPI spec

- Dockerfile-bats
- test/common.bash
- test/domains/domain-records.bats
- test/domains/domains-tags.bats
- test/domains/master-domains.bats
- test/domains/slave-domains.bats
- test/linodes/linodes.bats
- test/tags/tags.bats
- test/test-runner.sh
- test/volumes/create-volumes.bats
- test/volumes/list-view-update-volumes.bats
- test/volumes/resize-volumes.bats
* Adds tests for Tags
* Adds tests for adding tags to Volumes/Domains/Linodes
*  Broke out the `run linode-cli` commands to new lines for each param for better readability.
* Updated assertion text
* Disabled a few tests due to known bugs, recorded the bug numbers as the params for the skip method
* Added tags tests to docker entrypoint command
```bash
bats test/domains test/linodes test/volumes test/tags
```
> Add tags tests, refactor existing tests

- Dockerfile-bats
- test/common.bash
- test/nodebalancers/nodebalancers.bats
*Fair **warning**, running the automated CLI tests will remove all entities on your account. Please update your CLI configuration profile to a test user before running!*
* Added tests for nodebalancer creation, creating a nodebalancer configuration profile, adding a node to the nodebalancer, editing an existing profile, adding an additional profile, removing a profile
* Updated the CLI tests dockerfile to suppress warnings about API versions by default
* Added removeAll utility method (will potentially refactor existing tests to use this instead of specific "removeLinodes" "removeDomains" etc methods.
* Assumes you have the bats framework installed locally (`brew install bats-core`)
```bash
bats test/nodebalancers/nodebalancers.bats
```
* and plz read the test code
> ARB-771 - Nodebalancers BATS Smoke Tests

- linodecli/configuration.py
Proposing this language change so that the coaching text matches the interface seen by the user.
> Personal Access Token coaching text matches interface

- linodecli/plugins/k8s-alpha.py
In some cases with Python 2, linode-cli configuration variables
would be parsed as unicode type (although they did not contain
any multi-byte characters). Without this fix those variables
would produce an invalid and unusable Terraform config.
Shoutouts to @qtrain for reporting this.
> fix: (k8s-alpha) Support unicode Terraform variables

- Dockerfile-bats
- test/nodebalancers/nodebalancers.bats
* Removes fetching the open api spec from inside the container.
* Instead, save the openapi spec outside the container context and pass in the filename as a build argument.
* Feel free to ping me for further instructions on testing this if needed
> Fix spec fetching on alternative environments

- Dockerfile-bats
- test/nodebalancers/nodebalancers.bats
Reverts linode/linode-cli#95
This change appears to have broken the builder, rolling back for now.
> Revert "Fix spec fetching on alternative environments"

- linodecli/configuration.py
It turns out that using the environment variable to store the token can fail because the check for merging the configured settings and the command line supplied settings relies on `token` being present in the configuration. I hadn't noticed because I had already done a `configure` beforehand which stored a valid token in the `DEFAULT` user.
This PR fixes that issue by letting the configuration merge happen when the environment variable is defined.
Sorry for not catching this sooner! If you'd like me to open an issue for tracking purposes, let me know.
Cheers,
> fix: Allow merging of settings when token is not present in config

- Dockerfile-bats
- Makefile
* The openapi spec is now hosted at https://developers.linode.com/api/docs/v4/openapi.yaml this PR updates some references in the source to reflect this.
* Updated Makefile spec path, Dockerfile to new spec path.
> Update path to openapi spec

- linodecli/cli.py
* This PR changes the version comparison warning to only print the warning when the spec version returned by the API is a major or minor version greater than the CLI spec.
Example:
```
API Spec - 4.0.5 
CLI Spec - 4.0.6  # CLI was printing a warning prior to this PR, now it will not complain
```
> Do not print warning when API Spec's patch version is greater than CLI Spec

- linodecli/__init__.py
- linodecli/output.py
- linodecli/response.py
Closes #67
As requested, prints out output in a github-styled markdown format.
Example usage: `linode-cli regions list --markdown` outputs this:
| id | country |
|---|---|
| us-central | us |
| us-west | us |
| us-southeast | us |
| us-east | us |
| eu-west | uk |
| ap-south | sg |
| eu-central | de |
| ap-northeast | jp |
| ap-northeast-1a | jp |
> Added Markdown output format

- linodecli/cli.py
This is for @jfrederickson
Plugins sometimes need to use more complex filtering than the CLI
provides by default.  This allows plugins only to specify filter headers
as Python dicts, and overrides whatever was passed in the CLI command.
> Allow plugins to provide arbitrary filter headers

- linodecli/plugins/k8s-alpha.py
**NOTE:** Requires https://github.com/linode/linode-cli/pull/107
Currently, we set hardcoded instance types for both nodes and
masters. However, the linode-cli lets you specify a default type for
newly created Linodes.
Ideally, we would like to respect that choice, however K8s masters do
require 2 VCPUs at minimum. Since the available plans are available
through the API, we can look up the user's configured default type to
see if it meets this constraint. If it does, it's fine to use that. If
it doesn't, we pick the smallest plan that meets this constraint. (In
this case the user's default is smaller than the minimum, so they're
probably looking to deploy smaller Linodes if possible.)
Command output of this running after changing my default Linode type to g6-standard-8: …
> Dynamically set default Linode type for deployed K8s masters

- test/common.bash
- test/linodes/backups.bats
- test/linodes/linodes.bats
- test/linodes/power-status.bats
- test/linodes/rebuild.bats
- test/linodes/resize.bats
* It occurred to me that the timeout logic preventing infinite loops was not sound. These while loops are used to wait for linodes/entities to be provisioned/booted/etc.
* Rewrote every while loop to definitely meet the condition to timeout after 180 seconds.
* My bad
> Tests - Fix while conditional timeouts

- linodecli/configuration.py
- linodecli/plugins/README.md
- linodecli/plugins/__init__.py
- linodecli/plugins/k8s-alpha.py
Plugins may want to store persistent configuration data on a per-user
bases.  Instead of having them manage that themselves, this allows
plugins to use the Linode CLI's config in a uniform manner to store
persistent data.
All plugin config items' keys begin with `plugin-` followed by the
plugin's name.  Keys are stored per-user in the config, so multiple
users may have different settings configured.
This is not presently in use, but it might come in handy for some
upcoming plugins that may or may not be in the works ;)
> Added support for plugin configuration

- README.rst
- examples/third-party-plugin/README.md
- examples/third-party-plugin/example_third_party_plugin.py
- examples/third-party-plugin/setup.py
- linodecli/__init__.py
- linodecli/plugins/README.md
- linodecli/plugins/__init__.py
This adds a new command, `register-plugin`, which loads the python
module supplied by the user and checks that it is a runnable CLI plugin
before registering it to the CLI's config.  On further invocations of
the config, this plugin will be available.
Third party plugins require two things:
1. A `call` function that matches the expected signature
1. A `PLUGIN_NAME` constant that defines how the plugin should be called
This PR needs the following:
> Added third-party plugin support

- linodecli/plugins/ssh.py
This replaces #72.
Adds a new plugin, `ssh`, which is invoked as follows:
```bash
linode-cli ssh root@my-linode-label
```
The username piece is optional and defaults to the user invoking the CLI
(as normal ssh behavior).  This is basically a proxy for finding a
public IP address to ssh into the Linode with by searching for a Linode
with the given label.
If no Linode with the given label exists but other Linodes are found
that are close, those labels are output as a suggestion.
All arguments after the `[USERNAME@]LINODE_LABEL` are passed on to ssh
as normal.
Big thanks to @displague and @jfrederickson for their feedback regarding
this plugin.
> Adds `ssh` plugin

- test/events/events.bats
* Adds tests for listing, viewing, marking as read/seen events.
(Assumes you have bats installed), if not, see the readme.
```
cd test
bats events
```
> Added: Events BATS tests

- test/domains/domain-records.bats
- test/domains/master-domains.bats
- test/linodes/backups.bats
- test/linodes/resize.bats
* Fixed assertions for backups tests
* Fixed the setup for the resize tests, as this test would create a linode prior to each test and remove it after each (took a lot more time)
```bash
cd test
RUN_LONG_TESTS=TRUE bats linodes/backups.bats linodes/resize.bats
```
> Fix - Resize and backups Tests

- linodecli/cli.py
- linodecli/operation.py
- linodecli/plugins/obj.py
This shouldn't be merged yet :wink:
Adds the `obj` plugin, allowing invocation of Object Storage commands.
Also automatically provisions Object Storage Keys for the account if
none are saved to the config, and helps users request access to the
Early Access Program if they aren't in it yet.
> Added `obj` plugin to support Linode Object Storage

- test/linodes/backups.bats
- test/ssh/distro-and-connection-check.bats
- test/ssh/ssh.bats
* When written, there was only one alpine distro option, now there's multiple. Updated the tests to use the first alpine image in the list.
> Fix: SSH bats tests

- linodecli/plugins/k8s-alpha.py
This closes #131
After the Terraform command as been found, we can run `terraform
version` and compare it against our minimum and maximum versions.
Currently, those versions are v0.11.14 and v0.12.0.
The minimum version is an inclusive check, where v0.11.14 is supported.
The maximum version is an exclusive check, where v0.12.0 is not
supported.
It is not clear if Terraform uses true semantic versioning, but we
assume that the "major.minor.patch" are all going to be integers for now.
> Check Terraform Version in K8s Plugin

- linodecli/__init__.py
- linodecli/cli.py
- linodecli/operation.py
- linodecli/response.py
This is a fix for #106
Args that are not picked up by the argparse are being treated as
strings. A way around this is to add the specific argument,
'--entity.id', to argparse and treat it as an 'int'. We also suppress
the argument when displaying the "help" message.
> Add entity.id to argparse for int Conversion

- linodecli/plugins/obj.py
Had trouble deploying locally to test this, however I did run this code through multiple tests in an online IDE using various bite sizes and it continually worked successfully. 
This code converts the bytes output of a bucket size `linode-cli obj du` to human readable sizes. (KB, MB, GB, TB etc..) instead of just bytes, for easier to read sizes for our customers.
> Update: Converts bucket size output to human readable bytes

- linodecli/cli.py
- linodecli/operation.py
- linodecli/response.py
Closes #151
This was introduced in #141 - by parsing filter arguments as their
declared types in the spec, we were unintentionally turning "tags" into
an array of characters (it's defined as an array in the spec), so
`--tags test` would result in an header of `X-Filter: '{"tags":["t","e","s","t"]}'`,
which the API would balk at (correctly).
This change now captures the declared _item type_, and expects that for
any filterable attribute that is declared as an array.
@patthiel, we should add a test for filtering requests with tags to
prevent future regressions in the same vein.
> bug: Fix filtering by tags (and other arrays)

- linodecli/plugins/obj.py
Closes #159
It turns out that if you have more than 10 characters worth of disk
usage, the padding code broke.  This initialized `padding` to `""`
before setting it for smaller strings to avoid the break.
> Fix unbound local error in padding OBJ disk usage

- linodecli/operation.py
Closes #166
It looks like in many cases, the original lists remained after the
objects were reconstructed, causing the eventual parsing to JSON to
fail.  This removes the input lists after reconstructing the expected
objects to allow parsing to JSON to succeed.
> bug: Fix handling lists of objects

- linodecli/plugins/k8s-alpha.py
This adds a deprecation notice for the k8s-alpha plugin, which will be removed on March 31, 2020.
The following message is displayed on any invocation of the plugin.
```
┌────────────────────────────────────────────────────────────────────────────────────┐
│ This Plugin is Deprecated!                                                         │
│                                                                                    │
│ The k8s-alpha CLI is deprecated. On March 31st, 2020, it will be removed from      │
│ the linode-cli. After March 31, 2020, you will no longer be able to create or      │
│ manage clusters with this built-in k8s-alpha CLI plugin.                           │
│                                                                                    │
│ You will still be …
```
> Add deprecation notice for k8s-alpha plugin

- linodecli/__init__.py
This closes #153
Presently, `--json` simply outputs the normal fields as a JSON object,
with no special formatting or considerations, and it's up to the caller
to request `--pretty` and/or `--all` depending on their use-case.  This
change now enables `--all` for all JSON output, and enabled `--json` by
default when calling with `--pretty`.
`--all` can still be overridden via `--format`, which, if provided, will
trim down the resulting JSON object to only the named fields.
`--pretty` not forces json output in a pretty format.  This flag did nothing
otherwise, so this should be safe to do.
> Improved JSON output

- linodecli/__init__.py
- linodecli/cli.py
This closes #169
This is something I frequently jam into the CLI (much less gracefully)
during development of new features, to better see what's actually going
on.  Since it was requested as a feature, I figure it doesn't hurt to
include in the official build and save myself time going forward.
I based the actual output on curl's `-v` option, which I use for the
same purposes fairly regularly.  I'm open to other ideas, though.
Example output: 
```
$ linode-cli --debug linodes list --label Demo2
> GET https://api.linode.com/v4//linode/instances?page=1
> Authorization: Bearer [REDACTED]
> Content-Type: application/json
> User-Agent: linode-cli:2.13.1
> X-Filter: {"label": "Demo2"}
> Body:
>
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 13 Mar 2020 18:55:23 GMT
< Content-Type: …
```
> Added --debug flag for printing HTTP request details

- linodecli/plugins/obj.py
Closes #174
Previously, large files were sent as normal uploads, causing a long
upload time followed by a `EntityTooLarge` error.  This is because s3
has a maximum size for file uploads; this isn't the maximum size for
objects, mind, but for individual uploads.  Files larger than this size
must be uploaded in multiple parts.
This change supports uploading files as multiple parts.  I tested it
with some fabricated large files made with this command:
```bash
dd if=/dev/zero of=file-to-upload bs=1024 count=0 seek=20240
```
> Handle multipart uploads correctly

- linodecli/plugins/obj.py
Closes #178
Previously, there was no way to regenerate your object storage keys
without manually editing the CLI's config, which is a pretty lousy user
experience.  If you were to delete the keys in cloud, for example, the
CLI would be stuck attempting to use them for requests to Object
Storage.
This change adds the "regenerate-keys" command to the `obj` plugin,
allowing object storage keys to be regenerated in case they become
expired or otherwise don't work.
> Allow regenerating Object Storage keys

- linodecli/plugins/obj.py
Closes #181
When the object storage plugin lists bucket usage via the `du` command,
the size of each bucket is converted in KB, MB, or GB to present a more
human-friendly interface.  Due to an oversight, the total size of all
buckets was not converted to a human-friendly value in the same way, and
is being displayed simply as total bytes.
This change refactors the code that did the conversion out into its own
function, and calls it for both bucket totals and the grand total of
usage in a cluster.
> Make total size human-readable in `linode-cli obj du` output

- linodecli/cli.py
The CLI's spec parser currently makes a lot of assumptions, and one is
that paginated responses will have a `$ref` for their data, instead of
listing the schema directly.  This isn't required by OpenAPI, and for
the first time it isn't the case in our spec.
This change handles non-`$ref` paginated response data.
> bug: Handle paginated responses without $refs

- README.rst
- linodecli/plugins/obj.py
This is for @phillc
Previously, the `obj` plugin would require a config file to use to
get/store its object storage keys.  This isn't great for scripting.
This change allows those keys to be provided via flags to the plugin.
To invoke the plugin without a config, do something like this:
```bash
TOKEN=$API_V4_TOKEN linode-cli obj ls --access-key $ACCESS_KEY --secret-key $SECRET_KEY
```
Should this be pulled from the environment instead of the command line?
> Allow invoking obj plugin without config file

- linodecli/plugins/README.md
- linodecli/plugins/obj.py
Does the following:
- Adds a new OBJ plugin configuration for default cluster
- Removes the default cluster value of 'us-east-1' (to match image/region/type value behavior)
- Adds an OBJ command to configure the plugin (`linode-cli obj configure`)
- Respects `--no-defaults` for cluster value
- If no cluster is specified and no default is set, will ask the user to configure a default (unless `--no-defaults` is used, then just raises an error)
- Allows `--help` to be used for an OBJ command (ex. `linode-cli obj ls --help`) without a cluster and without a valid OBJ key
> Added a default cluster configuration for OBJ

- linodecli/operation.py
Closes #200
As it is now, the CLI either accepts passwords on the command line, or
interactively.  The interactive option was added to allow more secure
password entry, but it doesn't cover the automated case as mentioned in
the above issue.
This change implements the suggestion included in #200 to accept
passwords via environment variables to allow secure entry in a
non-interactive setting.  The CLI now gets the values for password
fields like so:
* If a password was given on the command line, use it
* If not, is an environment variable is set for the field, use its value
* If not, prompt for a password
This preserves backwards-compatible behavior while allowing the
environment to be considered.
The CLI will expect environment variables to match the CLI's argument
name, all uppercase, …
> Accept passwords from environment

- linodecli/plugins/obj.py
CC @phillc 
Previously, the obj plugin skipped objects with `/` in their names,
which is a somewhat perplexing choice I'd made when originally
implementing it.  This change brings the behavior more inline with s3cmd -
objects are listed with `/` as a delimiter, and prefixes can be
specified after the bucket name.  For instance:
```
$ linode-cli obj ls prefix-test
DIR  prefix/
2020-08-11 17:50  8    testfile3
$ linode-cli obj ls prefix-test/prefix/
2020-08-11 17:50  4  prefix/testfile
2020-08-11 17:50  5  prefix/testfile2
```
> Handle Prefixes in Obj Plugin

- README.rst
- linodecli/cli.py
- linodecli/operation.py
Closes #201
Previously, only "ssl-cert" and "ssl-key" formatted fields were
accepted as file paths (and then only if the input looked like a path
and a file existed at it); this change brings that behavior over to
other fields.  The linked docs PR below ties this into the StackScript
"script" field, but it can be used with any field now using a new spec
extension: `x-linode-cli-format`.  As per the included documentation in
this PR, the only valid value is "file" at present; the intention is
that this overrides the "format" given in the OpenAPI spec, but only in
the CLI, and only if present.  Any field with this format will inherit
the above-described path-checking behavior.
I also sorted the spec extension in the README, because they were all out of sorts.
> Accept StackScript scripts from file

- README.rst
- linodecli/cli.py
- test/clean-accounts.sh
- test/common.bash
- test/lke/clusters.bats
The `lke cluster-create` command is unique in the CLI in that it accepts
a list of dicts whose contents may themselves contain a list.  The CLI
didn't have a good way of disambiguating which element of the outer list
you intended inner list elements to belong to.  This made using the
endpoint impossible.
This change allows the spec to specify that an attribute is accepted as
JSON using the `x-linode-cli-format` extension; if the format is set to
"json" this way, the CLI will stop parsing sub-objects or list items and
accept the entire blob as JSON.  This fixes the above issue with the
below-linked docs PR merged.
> Accept nested lists

- test/lke/clusters.bats
Running the tests this morning, we got this failure:
> node_pools[0].type,The Linode type g6-nanode-1 is currently not supported by LKE
That must be new, as these have passed before.  Anyway, g6-standard-1
should work, so we're using that now.
> Change LKE tests to deploy g6-standard-1 nodes

- linodecli/cli.py
- linodecli/operation.py
This was pointed out by @adammohammed
This impacts the `object-storage keys-create` operation, and by
extension the `obj` plugin for new users.
This behavior didn't matter before now, which is probably why it went
unnoticed.  The new `bucket_access` argument to `POST /object-storage/keys`
does behave differently when given an empty list, however, and sending
it along caused the generated keys to have no access to anything.
> Don't send empty lists in requests

- Dockerfile-bats
- Makefile
- README.rst
- linodecli/__init__.py
- setup.py
@Dorthu I did a find/replace for any instances of what will be the old URL for the OpenAPI spec and updated them to the new location.
> Updated OpenAPI spec URL for new docs site launch

- README.rst
- linodecli/__init__.py
- linodecli/cli.py
Closes #194
This command prints shell completions for the requested shell to stdout
and exits.  Presently, only bash is supported, but adding support for
other shells should be simple.
> Added linode-cli completion command

- linodecli/__init__.py
- linodecli/configuration.py
- linodecli/plugins/obj.py
Closes #214
Previously, the CLI Configuration was initialized expecting to load a
config even if `--help` was passed in, which is unintuitive behavior
because the config will prompt for configuration immediately if a file
isn't found.  This was further complicated by the `obj` plugin, which
manages its own configuration and would fail if the CLI wasn't
configured when it was invoked, even with only a `--help` command.
This change is intended to make unconfigured user of the CLI easier by:
- Allowing `--help` commands to run without configuration
- Allowing the `obj` plugin to run `--help` commands without
configuration
- Providing better errors in the `obj` plugin, namely around cluster,
to allow users without a config to easily identify and remedy common
issues.
This should be tested …
> Run --help without a config in CLI and obj plugin

- linodecli/configuration.py
This was pointed out by @caker
When configuring multiple users, the CLI will prompt you to set the user
you're configuring as the active user, used by default when making
requests.  It also skips this question the first time you're configuring
the CLI.  However, confusingly, it still asks even if the user you're
configuring is already the active user, which happens if you only have
one user configured (and are updating their token).
This change removes the prompt to set the newly-configured user as
active if they are already the active user, and also matches the new
language in Cloud Manager for creating a token.
> Fix configuration behavior

- MANIFEST.in
- README.rst
- linodecli/configuration.py
- linodecli/oauth-landing-page.html
- requirements.txt
- setup.py
When I started using the GitHub CLI, I was very impressed with its OAuth-based configuration in the terminal, so I ported the feature over to the Linode CLI.  This is how a configuration works with it:
```
$ linode-cli configure
Welcome to the Linode CLI.  This will walk you through some
initial setup.
How would you like to configure the CLI?  [W]eb or [t]oken?
'w' for web or 't' for token: w
Your browser will be directed to this URL to authenticate:
https://login.linode.com/oauth/authorize?client_id=e3dc6ddb291b4709ae54&response_type=token&scopes=*
If you are not automatically directed there, please copy/paste the link into your browser
to continue..
Configuring dorthu
```
Not visible above is a browser being opened, directed to the authorization URL, which then redirects back to …
> OAuth-Based Configuration

- linodecli/configuration.py
This was verified as working, so we should allow it.  This is the
default browser on ElementaryOS
> Added epiphany browser to known working web browesrs for auth

- linodecli/__init__.py
Closes #235
While `--skip-config` does allow you to find the version without a token
provided, there's no reason to prompt for it at all, and I can see how
this would be disruptive.
This change treats `--version` as `--skip-config` when deciding if the
user should be prompted for configuration if none is present.
> Don't require configuration when running `--version`

- linodecli/configuration.py
Closes #239
If using the CLI with an environment-defined token (`LINODE_CLI_TOKEN`),
populating defaults in a request would fail with a
`configparser.NoSectionError` as it attempted to load defaults for an
unconfigured user.
This change checks to see if the user is configured before attempting to
apply defaults, and if so returns the namespace given instead of
attempting to update it.
> bug: Fixed populating defaults when no configuration is present

- linodecli/plugins/image-upload.py
The new POST /images/upload endpoint allows users to initiate an image
upload and returns a URL to upload the image data to.  While this can be
worked out on the command line, it's much more convenient to have a
plugin that does the entire process, accepting a file path, calling
the new endpoint, and actually handling the upload all in one command.
This new endpoint must be added to the docs before it can be supported
in this plugin.  During the beta period, this endpoint will not be
available to all users, so this plugin offers a reasonable error message
for users who attempt to invoke it and do not yet have access to it.
> new: Added image-upload first-party plugin

- linodecli/plugins/image-upload.py
Closes #243
The CLI is most useful if it contains all the information you need to
use it; image requirements for successful uploads and deployments are
definitely included in that.
The help now appears as:
```
$ linode-cli image-upload --help
usage: linode-cli image-upload [-h] [--region [REGION]] [--label [LABEL]] [--description [DESC]] FILE
positional arguments:
FILE                  The image file to upload. Should be a raw disk image compressed with gzip, in .img.gz format. We recommend using unpartitioned images with an ext3 or ext4
filesystem.
...
```
> fix: Document image-upload file requirements

- linodecli/plugins/obj.py
Closes #236 and #225
A much-requested feature of the obj plugin was to add the ability to
delete buckets that aren't empty, or otherwise remove many objects in
one operation.  Unfortunately this has to happen client-side, so it can
take a while for large buckets.
This change adds a `--recursive` flag to `linode-cli obj rb` that will,
if given, remove all objects from the bucket before removing the bucket.
As implemented here this will not abort in-progress multi-part uploads
or clear stale object versions; that may be added later if it's
necessary (but if such things exist, they will prevent the bucket
deletion from completing successfully).
> Allow recursively deleting not-empty buckets

- linodecli/plugins/image-upload.py
Closes #250
Right now, the `image-upload` plugin just attempts to upload whatever
it's given, but that can waste a lot of time.
This change checks that the compressed size is no larger than the
maximum allowed (5GB) before initiating the upload.
This change does not attempt to catch cases where the _uncompressed_
size of the image is larger than allowed; the maximum uncompressed size
is not constant, and the CLI has no way to know if an Image uploaded
will end up being too large when it gets there.
> fix: Check Image upload size before attempting upload

- linodecli/cli.py
Closes #255
The spec for LKE Node Pools included deeper `$ref` nesting than the
CLI's parser supported.  This change resolves one more level of `$ref`,
allowing node pools counts to be updated easily.
This isn't an awesome fix; the real problem here is the fragility of the
CLI's spec parser, and the real fix is to implement a better spec
parser, as #218 attempted to do.  That effort should be completed to
resolve all like issues that may be found in the future.
> bug: Resolve nested refs

- README.rst
- linodecli/cli.py
- linodecli/configuration.py
- linodecli/operation.py
This should fix the `linode-cli tickets create` action.
The Linode CLI, when being configured, accepts default values for
"region", "image", and "type".  These values were previously added to
every input for a PUT or POST endpoint, and then parsed out as normal.
This had the effect of defaulting those values to the configured
defaults for actions like `linodes create` or `nodebalancers create`
without additional interaction.
However, the `tickets create` action recently began accepting
`--region`, but only for certain types of tickets.  This caused ticket
creation to fail through the CLI if a default region was configured,
unless `--no-defaults` was given, or unless the specific ticket type was
being opened.
This change allows the spec to specify which actions should use which
defaults, …
> bug: Only allow requested defaults to actions

- test/lke/clusters.bats
Currently, this test is failing with an "k8s_version,k8s_version is not valid".
Sure enough, it looks like 1.19 was retired recently.
This change updates the tests to use 1.21, the most recent version.  In
the future they may even need to get this value dynamically.
> Updated --k8s-version in LKE test

- linodecli/plugins/image-upload.py
Closes #262
Looks like in https://github.com/linode/linode-cli/pull/257 I changed
the signature of this function, and didn't realize I was using it in a
plugin, which caused the plugin to break.
This change adds the correct allowed default for this function (we want
default regions for image uploads).
> bug: Fix image-upload plugin

- README.rst
- linodecli/response.py
- requirements.txt
- setup.py
Closes https://github.com/linode/linode-cli/issues/231
The colorclass module is not compatible with Python 3.10, and is
currently [archived on github](https://github.com/Robpol86/colorclass)
with issues open about future compatibility issues and no real
suggestion of movement.
This change replaces `colorclass` with the few color codes that were
actually used so far, which removes the dependency entirely and should
allow the CLI to work on python 3.10.
This appears to work where I've tested it, and from what I read it aught
to work the same on Windows too, but I'd like someone to give it a spin
first to be sure.
> Remove dependency on colorclass

- test/kernels/kernels.bats
Removed the xen column from the expected column list - this is no longer supported
and the key has been removed from the API spec in version 4.108.0.
Also added two new(ish) columns to the expected list - deprecated and built.
> Altered expected columns in the kernel test

- linodecli/cli.py
- linodecli/operation.py
Related to #273
Right now, the output you get when you call a CLI operation without
arguments is as follows:
```bash
$ linode-cli networking ip-update
usage: linode-cli [-h] [--rdns rdns] address
linode-cli: error: the following arguments are required: address
```
The "usage" line in that output is clearly wrong, as you did not invoke
`linode-cli` by itself.  This change adds the command/action you
provided into that output to make it display correctly:
```bash
$ linode-cli networking ip-update
usage: linode-cli networking ip-update [-h] [--rdns rdns] address
linode-cli networking ip-update: error: the following arguments are required: address
```
> bug: Fixed error output for CLI operations

- test/volumes/list-view-update-volumes.bats
This is related to https://github.com/linode/linode-cli/pull/274
In #274, I changed the output when a command is entered improperly to
include the command and action the CLI was processing when the error
occurred, which mimics what was entered on the terminal.  I didn't
realize tests were checking for the old output.
This change updates tests to look for the new output instead of the old
format.
> bug: Tests should accept new error output

- test/volumes/list-view-update-volumes.bats
Tests regularly fail, delaying CLI releases, because there are other
Volumes on the test account, and commands referencing a `$volume_id` are
given a list of IDs instead of just the one they expect.
This change sets `$volume_id` to a single Volume's ID, which should
allow tests to continue even if there are unexpected volumes on the
account.
> bug: Make tests more durable

- Dockerfile-bats
Recently the openapi.yaml file moved.  Redirects were set up for the old
location, but the Dockerfile for our tests did not follow them, and so
the tests began failing.
This change updated the Dockerfile for the bats tests to follow
redirects when fetching the spec file.
> bug: Follow redirects when downloading spec

- README.rst
- linodecli/cli.py
This is for the future.
Python2 has been EOL since 2020.  This repo should no longer be
recommending installs via python2, and it should correctly show python3
commands when suggesting how to upgrade itself.
> ref: Stop recommending python2

- linodecli/cli.py
- linodecli/operation.py
In the process of attempting to free the namespace for CLI Args that
conflict with URL Params, I accidentally overwrote the stored param
string for all methods under a given path.  This caused the operation
`linode-cli users view` to have a param `username_`, but the URL to
continue to be `/account/users/{username}`, as the param's name was
updated when processing `linode-cli users update` (which has a
`--username` arg and a `username` param, causing the param to change to
`username_` and the url to change to `/account/users/{username_}`).
This change copies all params, so that when they are updated, only the
copy local to this method is updated.
> bug: Fix `linode-cli users view USERNAME`

- linodecli/cli.py
Related to https://github.com/linode/linode-api-docs/pull/581
It is possible that every operation in a path is skipped in the CLI via
the `x-linode-cli-skip` spec extension.  In this case, that path's
command should not be present in the CLI at all, as it would have no
actions associated to it.  The above-linked PR introduces the first
paths that are entirely skipped in this way.
This change removes all empty commands from the CLI after building the
entire command/action structure.
> bug: Remove commands with no actions from recognized commands

- linodecli/__init__.py
Python 2 was sunset on Jan 1st, 2020.  We have continued to support
python2 this long because many users still use it, however as python3
support has grown and libraries continue dropping support for python2,
it is becoming increasingly difficult to maintain the CLI with python2
supported.
This change adds a warning to users running the CLI under python2 that
support will be dropped in a future version, and includes a link to our
official guide on how to upgrade your installation.  As usual,
`--suppress-warnings` silences this warning, and the warning is output
to `stderr` to allow users to redirect `2>/dev/null` to ignore it as
well.
In the last version that supports python2, this warning will be changed
to note that support _has been_ dropped, and that upgrading to a python3
install is …
> new: Warn python2 users of planned dropping of support

- linodecli/cli.py
This fixes the `linode-cli databases mysql-update` command.
This command accepts an array, called `--allow-list`.  This is
unremarkable, except that the spec nests this list under three layers of
references.  That's valid, but the CLI didn't handle it well.
This is one of the problems that a better spec parser would likely solve
for us immediately: https://github.com/linode/linode-cli/pull/218
This change repeatedly resolves references in args until there are none
left, handling layers of references for a single argument.
> bug: Resolve references in references

- README.rst
- linodecli/response.py
Closes #297
Database Types return (currently) three different engine types with
their prices, in nested lists within a container object.  This wasn't
handled well when flattening API responses into table rows.
This change allows multiple, exclusive nested lists to be flattened into
output table rows.  This _does not_ support multiple unrelated nested
lists; all lists will be parsed and returned as individual values.
For example, this API response:
```json
{
"id": "g6-nanode-1",
"label": "DBaaS - Nanode 1GB",
"engines": {
"mysql": [
{
"quantity": 1,
"price": {
"hourly": 0.0225,
"monthly": 15
}
},
{
"quantity": 2,
"price": {
"hourly": 0.0375,
"monthly": 25
}
},
{
"quantity": 3,
"price": {
"hourly": 0.0525,
"monthly": 35
}
}
],
"postgresql": [
{
"quantity": 1,
"price": {
"hourly": 0.0225, …
```
> new: Support multiple exclusive nested lists

- test/common.bash
- test/users/users.bats
I came to report an issue retrieving users, but found @patthiel had already opened an issue for it (https://github.com/linode/linode-cli/issues/42).
I didn't look into the details of why it is failing. It seems like @Dorthu had a good idea of what was going on. Thought I could help and write some tests for it. Taken almost 1:1 from tags.bats, but they do exemplify what I was going to report.
p.s. no clue of this `localhost` email is accepted by the API. The warning when trying to test it locally about deleting all my things scared me, so I'm letting CI here do it for me.
> test user creation, deletion, retrieval, and listing

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- CONTRIBUTING.md
- README.rst
This change adds the standard Linode `CONTRIBUTING.md` file as well as various templates for creating issues. This follows the layout of other Linode org repositories (see: [terraform-provider-linode](https://github.com/linode/terraform-provider-linode), [ansible_linode](https://github.com/linode/ansible_linode))
> doc: Add CONTRIBUTING.md and issue templates

- test/clean-accounts.sh
- test/common.bash
- test/test-runner.sh
Allows us to use "linuke-keep" tag on Linode objects to prevent it from being automatically deleted by a test. Useful for testing on a Linode Account that has long term configurations for other work.
> linuke-keep safeguard for tests

- linodecli/__init__.py
This change resolves an issue that suggests a user is not properly configured when the config is not properly loaded. Particularly, this affects `--help`, `--version`, and `--skip-config` flags when `--as-user` is defined.
Resolves #309
> fix: Do not handle `--as-user` if config is not loaded

- linodecli/__init__.py
- linodecli/cli.py
- linodecli/operation.py
This change adds support for aliasing actions by defining multiple values for the `x-linode-cli-action` in the API spec.
For example, for GET `/linode/instances`:
```
x-linode-cli-action:
- list
- ls
```
would allow users to run either
```
linode-cli linodes ls
```
or 
```
linode-cli linodes list
```
Additionally, all aliases will be displayed on the help page as shown below:
See #149, https://github.com/linode/linode-api-docs/pull/708
> new: Add support for action aliasing

- Makefile
- README.rst
- linodecli/configuration.py
Allows users to configure a user to automatically set for Authorized_Users in Linode:Create, when you provide a --authorized_users field it will overwrite the default
resolves [#233]
> allowing default for Authorized_Users in Linode:Create

- Makefile
- linodecli/configuration.py
- warn users when using defaults which values are being used
- warning can be suppressed with `--no-headers` and `--suppress-warnings`
- added missing artifact to make clean
resolves [#58]
> output: print default values being used

- linodecli/__init__.py
- linodecli/cli.py
- linodecli/operation.py
This change allows the CLI to automatically bake API documentation URLs into command help pages. This is useful for providing additional documentation that may not already be available through the help page.
Resolves #247
> new: Link to endpoint documentation in command help page

- Dockerfile-release
This change installs the `boto` package during the OCI image build process. This is necessary for running the `obj` plugin.
> fix: Install `boto` in OCI image Dockerfile

- linodecli/response.py
This change adds an additional condition for gracefully handling empty (`{}`) endpoint dict responses. This resolves errors thrown when executing command such as `linode-cli longview plan-view` using the default plan type.
Resolves #220
> fix: Gracefully handle empty endpoint responses

- Dockerfile-release
This change drops the `VOLUME` instruction from the `Dockerfile-release` file. This is necessary as this instruction often caused permission errors in certain configurations. Users are still able to handle config persistence using volume mounts.
> fix: Drop VOLUME from OCI image

- .github/pull_request_template.md
This change adds a template that will be used by default on new pull requests. This is useful for standardizing the format of our PRs and encouraging detailed PR descriptions.
> doc: Add pull request template

- linodecli/plugins/firewall-editor.py
- linodecli/plugins/firewall.py
This change adds an interactive rule editor for Linode firewalls. This is necessary as it allows users to modify their firewall from the CLI without needing to manually specify every rule on update.
The editor can be accessed by running the following command:
```bash
linode-cli firewall-editor {firewall_id}
```
After discussing with the firewall team, it seems like automated
inserting of individual firewall rules isn't a great idea; the rules are
applied immediately as changes are made, and since these rules are
applied in order, with the first matching rule being acted on, it's easy
to accidentally set up an insecure configuration.  To make matters
worse, there is no good way to identify a single rule from the response;
labels are not required and don't have to be unique, and no other …
> new: Add interactive firewall rule editor plugin

- .github/release-drafter.yml
- .github/workflows/oci-build.yml
- .github/workflows/publish-pypi.yml
- .github/workflows/release-drafter.yml
- Dockerfile-release
- version
This change automates CLI releases through GitHub actions. This includes a release drafter, a new workflow for publishing releases to PyPI, and various changes to the existing OCI publish workflow.
**Releases should be cut using the following steps:**
1. A release is drafted automatically after every commit to `master`
2. Once a release is ready to be cut, a maintainer can simply modify and publish the release drafted in step 1.
3. After the release is published, two jobs will spawn to publish the release artifacts to DockerHub and PyPI respectively.
This release process requires a `PYPI_API_TOKEN` secret be exposed with access to only the `linode-cli` package.
This workflow has been tested against a fork of `linode-cli`.
In a private fork of this repo, push up the code from this branch …
> new: Add support for publishing to PyPI through GHA

- Makefile
- resolve_spec_url
This change alters the Makefile to dynamically resolve the latest OpenAPI spec URL from GitHub. This allows the CLI to be easily built from various spec versions and prevents any inconsistencies between GitHub and https://www.linode.com/docs/api/openapi.yaml.
Everything seems to work as intended from my local testing.
```
make build
```
```
make SPEC_VERSION=v1.139.0 build
```
```
make SPEC=https://www.linode.com/docs/api/openapi.yaml build
```
> new: Dynamically resolve latest GitHub OpenAPI spec URL

- .github/workflows/e2e-suite.yml
- linodecli/__init__.py
- linodecli/configuration.py
- test/common.bash
- test/domains/domain-records.bats
- test/linodes/linodes.bats
- test/linodes/power-status.bats
- test/linodes/rebuild.bats
- test/networking/networking.bats
- test/ssh/distro-and-connection-check.bats
- test/ssh/ssh.bats
- test/stackscripts/stackscripts.bats
- test/test-runner.sh
- test/volumes/attach-detach-volumes.bats
- test/volumes/list-view-update-volumes.bats
This change introduces a new end-to-end testing workflow that runs on all commits pushed to the `master` branch. Support for running acceptance tests on PRs will need to be added in the future as `/acctest` commands.
Additionally, this PR makes large changes to the existing Bats test suite to run consistently in an easily reproducible environment.
All tests are passing consistently locally.
The test suite can be tested locally by following the README instructions for running the entire test suite.
The E2E workflow can be tested by checking out this branch and pushing it to the `master` branch of a fork on GitHub.
An example workflow run can be viewed [here](https://github.com/lgarber-akamai/linode-cli/actions/runs/3631356432/jobs/6125881610).
> new: Add E2E test suite workflow and improve Bats test suite

- README.rst
- linodecli/__init__.py
- linodecli/cli.py
adds tab completions for Fish shell
added a note to the README about using `bashcompinit` to use existing bash tab completion to generate Zsh completion!
linode-cli completion fish
resolves: #194 and #281
shoutout to @someguy123 for the find!
> Adding completion for Fish Shell

- .github/workflows/e2e-suite.yml
- .github/workflows/release-drafter.yml
- README.rst
- examples/third-party-plugin/example_third_party_plugin.py
- linodecli/plugins/README.md
This PR changes all references to the `master` branch to the `main` branch. This is a preemptive change for using a dev/main branch model.
> ref: `master` -> `main` branch references

- Makefile
This pull request modifies the `make install` target to only install from the wheel package rather than from the source dist. This is necessary as installing from source dist may cause `permission denied` errors in CI.
`make install`
> fix: Only install from .whl in `make install` target

- .gitignore
- MANIFEST.in
- Makefile
- setup.py
This change modifies `setup.py` to bake the CLI version into `sdist` target archive. This is necessary as the CLI cannot infer the version when install from the source dist by default.
This change has been tested against the existing GHA release workflows.
```
make build && pip install --force dist/*.tar.gz
```
You can also test a pre-built source distribution using the following command
```
pip install --force --no-binary all linode-cli-testrelease
```
> fix: Properly bake version for `sdist` targets

- test/domains/master-domains.bats
This pull request corrects the `SOA_Email` substring check in the domain E2E test suite. This is in response to the corresponding Linode API change.
> fix: Correct broken substring check in domain E2E test 

- setup.py
This change alters `setup.py` to include the new `linodecli.configuration` package. This should resolve errors when attempting to run the E2E test suite or running the CLI after a `make install`
```
make install
linode-cli linodes ls
```
> fix: Add `linodecli.configuration` to setup.py packages

- linodecli/__init__.py
- linodecli/output.py
- tests/test_output.py
This pull request adds support for automatically truncating data for tabular output formats. Additionally, this change adds a `--no-truncation` field to disable this functionality.
e.g.
```
linode-cli lke kubeconfig-view 90162
Certain values in this output have been truncated. To disable output truncation, use --no-truncation. Alternatively, use the --json or --text output modes, or disable warnings using --suppress-warnings.
┌─────────────────────────────────────────────────────────────────────┐
│ kubeconfig                                                          │
├─────────────────────────────────────────────────────────────────────┤
│ CmFwaVZlcnNpb246IHYxCmtpbmQ6IENvbmZpZwpwcmVmZXJlbmNlczoge30KCmNs... │
└─────────────────────────────────────────────────────────────────────┘
``` …
> new: Add support for result output truncation

- .gitignore
- linodecli/plugins/obj.py
- pyproject.toml
Add [PEP 518](https://peps.python.org/pep-0518/) compliance by specifying build system.
See also: https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-pyproject-toml
> PEP518 Support

- linodecli/__init__.py
- linodecli/cli.py
- requirements-dev.txt
- test/cli/help.bats
- tests/test_cli.py
This change fixes an issue that would prevent aliased actions from displaying `--help` pages. Additionally, this pull request breaks out operation discovery logic into a `find_operation` CLI method.
Resolves #351 
```
make test
cd test && bats ./cli/help.bats
```
> fix: Add support for `--help` pages on aliased commands

- README.rst
- linodecli/__init__.py
- linodecli/helpers.py
- linodecli/operation.py
- test/cli/help.bats
- test/cli/host-overrides.bats
This change introduces a few new environment variables for dynamically controlling the target Linode API instance:
- `LINODE_CLI_API_HOST`
- `LINODE_CLI_API_VERSION`
- `LINODE_CLI_API_SCHEME`
These environment variables affect the API URL for both configuration and operations.
> new: Allow API overrides through the environment

- tests/conftest.py
- tests/test_api_request.py
- tests/test_cli.py
- tests/test_output.py
- tests/test_response.py
Putting global fixtures in `conftest.py` to allow pytest to automatically collect and use the fixtures without making manual imports.
> Move consistent fixtures to conftest.py

- linodecli/configuration/auth.py
We have a landing page in `linodecli/oauth-landing-page.html` but it was never used due to an incorrect path.
This PR fixes this issue and display it instead of the hard coded default landing page in the source code.
Another thing is that we can use Python's [`pathlib`](https://docs.python.org/3/library/pathlib.html) to replace the lower-level operating system APIs `os.path` for files and path manipulations in most situations, which makes it simplify and easy to understand.
> Fix Landing Page Path

- tests/test_plugin_obj.py
This change fixes a broken assertion in the `test_print_help` test.
```
make test
```
> fix: Fix broken assertion in OBJ test

- linodecli/cli.py
- linodecli/helpers.py
- tests/test_helpers.py
This pull request adds support for human-readable markdown links in summaries for both commands and arguments.
For example:
```
Here's [a relative link](/docs/cool) and [an absolute link](https://cloud.linode.com).
```
becomes:
```
Here's a relative link (https://linode.com/docs/cool) and an absolute link (https://cloud.linode.com).
```
```
make test
```
> new: Add support for human-readable markdown in summaries

- linodecli/cli.py
- test/linodes/linodes.bats
This pull request fixes an issue that would cause certain `readOnly` fields to display as valid updatable fields. For example, `linode-cli linodes update` supported the `--image` field despite this field being read-only.
```
cd test
bats linodes/linodes.bats
```
> fix: Use top-level `readOnly` value when reading arguments from refs

- linodecli/__init__.py
- linodecli/api_request.py
- linodecli/cli.py
- linodecli/configuration/helpers.py
- requirements.txt
- setup.py
We now require Python >= 3.6 in `setup.py`, so we can drop all the code that was for supporting Python 3.5 and lower versions.
Run your favorite linode-cli commands
> Remove efforts to support Python <= 3.5

- .github/workflows/unit-tests.yml
- Makefile
- linodecli/__init__.py
- tests/configuration.py
- tests/conftest.py
This pull request adds a GitHub Action workflow to run unit tests on pushes and pull requests.
Additionally, this PR makes some adjustments to the codebase to get unit tests working with an existing config. This includes a `LINODE_CLI_TEST_MODE` environment variable that can be used to globally toggle functionality that may not be compatible with unit testing.
`make test`
> new: Add GHA workflow for running unit tests

- linodecli/configuration/__init__.py
- tests/configuration.py
If the default value isn't set in the config or provided as a argument it will cause a error.
Now it checks if neither are provided and ignores it.
remove a default value from your config and attempt to create a instance
resolves [#378]
> fix: null values for defaults in spec

- tests/unit/configuration.py
Before this fix, if you set `LINODE_CLI_TOKEN` in your environment, the unit test would fail because it assumes that the token is not set and the cli would take input for the token.
`make test`
`export LINODE_CLI_TOKEN=<your token>`
`make test` (this may fail in the old version)
> Fix Unit Test

- Makefile
- tests/integration/test_plugin_image_upload.py
- tests/unit/test_plugin_image_upload.py
This change introduces unit and integration tests for the `image-upload` plugin. Additionally, it adds a `make testint` target for running integration tests.
```
make testint
make testunit
```
> new: Add integration and unit tests for the `image-upload` plugin

- tests/integration/test_plugin_ssh.py
It seems the password requirements were updated and the API requires a longer password now.
Ensure `boto` is installed and `LINODE_CLI_TOKEN` is set in the env.
Then `make testint`
> Fix SSH Plugin Integration Test

- tests/integration/conftest.py
- tests/integration/fixture_types.py
- tests/integration/helpers.py
- tests/integration/test_obj_plugin.py
Python `tempfile` module helps to clean up the generated files. Preventing junk files left when test cases fail.
`make testint`
> Put obj Plugin Integration Test Files in a Tempfile Directory

- .github/workflows/unit-tests.yml
This change adds the GITHUB_TOKEN environment variable to the `make install` command in the unit test GitHub Action. This should prevent rate-limiting and make the unit test workflow more reliable.
> fix: Use `GITHUB_TOKEN` in `make install` to prevent rate-limiting from GitHub

- .github/workflows/remote-release-trigger.yml
This pull request adds the necessary workflow for triggering automated CLI releases after the release of new OpenAPI spec versions.
The necessary secrets and environments have already been added to this project.
> new: Add workflow for releases triggered by linode-api-docs

- .github/workflows/e2e-suite-pr-command.yml
- .github/workflows/e2e-suite-pr.yml
- Makefile
This change adds support for the `/acctest` command, which allows maintainers to run integration tests on PRs using a command and commit hash. This implementation mimics the implementation for other DX-owned repos (terraform-provider-linode, ansible_linode, etc.)
The following environment variables will need to be added to the secrets of this repository:
- DX_ACCTEST_APP_ID
- DX_ACCTEST_PRIV_KEY
**NOTE: This change excludes bats tests due to the planned removal of bats in the near future. See #394**
```
/acctest sha=mycommitsha
```
```
/acctest sha=mycommitsha tests=test_plugin_image_upload.py::test_file_upload
```
See https://github.com/lgarber-akamai/linode-cli/pull/1
> new: Add support for `/acctest` command

- linodecli/plugins/__init__.py
Fixed an issue caused by my previous PR. The plugin name should not contains the extension of the file name (`.py`).
> Fix Plugin Discover

- linodecli/configuration/__init__.py
- linodecli/configuration/auth.py
This pull request resolves an issue that would prevent tokens created without account permissions from being configured using `linode-cli --configure`.
Resolves #398 
1. Create a token without account permissions
2. `linode-cli configure --token`
> fix: Resolve issue with configuration of tokens without account privileges

- .github/workflows/remote-release-trigger.yml
This change corrects the remote release workflow to point at the `main` branch.
> fix: Use main branch for remote release automation

- requirements.txt
- setup.py
This change adds the `packaging` package to `install_requires` and drops the version specifier from requirements.txt.
Thanks @okoriko!
> fix: Add packaging to install_requires and drop version specifier

- linodecli/configuration/helpers.py
This pull request fixes a bug that would cause a single token defined under the `[DEFAULT]` block without any defaults to throw an error.
```
make test
```
> fix: Ignore missing defaults when no default user is defined 

- setup.py
Fix missing packaging dependency in the setup.py file
relates to https://github.com/Homebrew/homebrew-core/pull/126192
Tested out in the homebrew CI.
> setup: fix required deps mismatch

- setup.py
The status of Python 3.6 is end of life, and may contains unfixed security issues and other bugs.
https://devguide.python.org/versions/#unsupported-versions
Other cloud provider's tools such as AWS and Azure dropped Python 3.6 support.
https://github.com/aws/aws-cli/blob/dd48afaaa8b9e682579b1a35109d910ca78aae01/setup.py#L51
https://github.com/Azure/azure-cli/blob/c02d63182860feab89da2502c46bae008b7a3fa2/src/azure-cli/setup.py#L176
It is the time for us to make an similar decision.
> Bump Python version requirement to 3.7

- README.rst
- linodecli/api_request.py
- linodecli/configuration/__init__.py
- linodecli/configuration/helpers.py
- tests/unit/configuration.py
- tests/unit/conftest.py
- tests/unit/test_api_request.py
Add the default values for database engines in CLI config. https://jira.linode.com/browse/TPT-1676 
Create MySQL and PostgreSQL database separately use default values including engine:
Overwrite the engine value:
> Add default values for database engines

- linodecli/plugins/obj/__init__.py
Noticed this while reviewing #440.
I suspect that `boto` used to output dates like this, and the format
changed in the conversion to `boto3`.
Current output:
```
$ linode-cli obj ls
2021-03-10 12:32:10.317000+00:00  example-bucket
```
This branch:
```
$ linode-cli obj ls
2021-03-10 12:32  example-bucket
```
`s3cmd ls` output (for reference - this plugin was originally based on
that):
```
$ s3cmd ls
2021-03-10 12:32  s3://example-bucket
```
> bug: Shorten datetime strings output from `linode-cli obj ls` operation

- linodecli/__init__.py
- linodecli/arg_helpers.py
- linodecli/output.py
- linodecli/plugins/firewall-editor.py
- linodecli/plugins/obj/__init__.py
- linodecli/plugins/obj/helpers.py
- requirements.txt
- tests/unit/test_output.py
Relates to #436 
The version of `terminaltables` used by this project has been archived for a few years now and was recently removed from the Arch community repository (which is what led me to embark on this PR). While the project may remain viable for some time to come, I propose the maintainers of `linode-cli` consider switching to [rich](https://github.com/textualize/rich), which offers much greater versatility when rendering rich text to the terminal in Python (even `pip` uses rich for its progress bar functionality).
I have made the necessary changes to the code in this PR.
- Updated `requirements.txt`
- Added `rich`
- Removed `terminaltables`
- Updated all instances of `terminaltables.SingleTable` objects throughout the project with equivalent `rich.Table` objects. The following …
> Replace terminaltables with rich

- README.rst
This change adds a brief description and link to the Linode CLI Marketplace GitHub Action.
> doc: Add link to the Linode CLI marketplace action

- .github/workflows/e2e-suite-pr-command.yml
When we created the acctest command workflows, GitHub doesn't support using `GITHUB_TOKEN` to trigger another workflow [but later they added some exception](https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/).
We used a workaround to generate a token as a GitHub App to trigger an `repository_dispatch` event to trigger the integration test. With the newly added exception, now I believe we can trigger the integration test directly by the `repository_dispatch` event triggered by the built-in `GITHUB_TOKEN`, and we can now remove the action that was used to generate GitHub App token.
Will only be testable in this repo after merging.
Success on my forked repo:
https://github.com/zliang-akamai/linodego/pull/2#issuecomment-1522 …
>  Simplified Acctest Command Dispatching Workflow

- .github/workflows/unit-tests.yml
- tests/unit/test_api_request.py
- tests/unit/test_completion.py
- tests/unit/test_configuration.py
- tests/unit/test_plugin_image_upload.py
- tests/unit/test_plugin_kubeconfig.py
- tests/unit/test_plugin_ssh.py
replaced all try and except blocks with pytest.raises for cleaner and proper assertion
since mock is part of python std lib, we can import it directly from unittest
> Fix error assertions and cleanup dependencies

- linodecli/operation.py
- linodecli/overrides.py
- tests/unit/test_overrides.py
This change introduces a new output override system that allows us to modularly add custom output logic for specific generated commands. This is useful for cleaning up outputs for endpoints with responses that may be too complicated to account for in the spec parser.
> new: Add support for output overrides and add `domains zone-file` override

- linodecli/plugins/obj/__init__.py
- linodecli/plugins/obj/website.py
Putting the website relevant functions into another file would make the code base more readable and well organised.
`export LINODE_CLI_TOKEN=<YOUR_TOKEN>`
`pytest tests/integration/test_obj_plugin.py`
> Put obj plugin website functions to another file

- linodecli/arg_helpers.py
- linodecli/helpers.py
- linodecli/plugins/obj/__init__.py
- linodecli/plugins/obj/buckets.py
- linodecli/plugins/obj/objects.py
- linodecli/plugins/obj/website.py
- requirements.txt
This pull request resolves an issue that would cause the CLI to crash (or 403) if an absolute path was provided when getting an object. Additionally, this change adds support for the `--suppress-warnings` argument in the OBJ plugin.
Resolves #451 
```bash
make test
pytest tests/integration/test_obj_plugin.py
```
> fix: Resolve issues with absolute paths in OBJ plugin and fix warning suppression logic

- README.rst
- linodecli/operation.py
- tests/unit/test_operation.py
This change improves the handling for nested list structures (e.g. Instance Interfaces) by implicitly detecting when the next list entry should be populated. This means that users do not have to explicitly specify empty values for null fields.
For example, see this command:
```bash
linode-cli linodes config-update 1234 5678 \
--interfaces.purpose public \
--interfaces.purpose vlan --interfaces.label my-vlan 
```
A user would intuitively expect this command to set the first interface to public and the second interface to a VLAN with the label `my-vlan`, however executing this command would generate this request body:
```json
{
"interfaces":[
{
"label":"cool",
"purpose":"public"
}
]
}
```
After this change, the request body is now generated as expected:
```json
{
"interfaces":[
{ …
```
> new: Improve handling for list structures

- linodecli/__init__.py
- linodecli/api_request.py
- linodecli/arg_helpers.py
- linodecli/cli.py
- linodecli/helpers.py
- linodecli/output.py
- tests/unit/test_cli.py
Provide a option for user to output all results without pagination.
Should we add some integration/unit tests for this? Will be working on that if necessary.
Create 1000 stackscripts in your account then run `linode --all-rows stackscripts ls --is_public false`
> Add `--all-rows` Flag

- linodecli/output.py
- tests/unit/test_output.py
This change resolves an issue with the `--no-headers` flag in table output mode which would cause the first row of content to be dropped.
```
make testunit
```
> fix: Resolve `--no-headers` flag for tabular output

- version
This change drops the logic that causes the CLI default to the latest annotated git tag, which causes installation issues when the repo is cloned directly from a branch or does not have the `.git` directory. If no version environment variable or baked file is defined, the version will now default to `v0.0.0`.
```
make install
```
> ref: Remove logic for resolving version from tag; failover to `v0.0.0`

- linodecli/configuration/__init__.py
- linodecli/configuration/helpers.py
- tests/unit/test_configuration.py
This change adds a `No Default` option to the `linode-cli configure` command that allows users to optionally clear a default if it is already defined in the existing config. This differs from the skip (enter) functionality in that the skip functionality retains the previous config value and the `No Default` option drops the config value.
> new: Add a `No Default` option when running the `configure` command

- Makefile
- requirements-dev.txt
Calling `setup.py` directly is now deprecated.
> Migrate build frontend to `pypa/build`

- Makefile
- requirements-dev.txt
- setup.py
`twine check` is necessary to ensure the package can be built and validated for publishing on PyPI.
`make lint` or see the GHA run result.
> Add twine check in lint workflow

- linodecli/plugins/obj/helpers.py
- tests/unit/test_plugin_obj.py
`linode obj du` produces correct output in almost all real-world cases, but it's off by a few orders of magnitude when 0 < size < 1024 (claims KB when should be bytes), and does stranger things whenever size happens to be a power of 1024, or whenever it is greater than 1 PiB.
One way to reproduce the bug is to create a bucket containing a single file whose size meets any of the above criteria, then run `linode obj du` against it. For example, the bucket below contains a single 415 byte file. `obj ls` reports the correct size, but `obj du` incorrectly claims a total of 415 KB:
```
$ linode-cli obj du
415.0 KB    1 objects  jafreche
$ linode-cli obj ls jafreche
2023-06-13 23:22  415  index.html
$ curl --silent …
```
> fix incorrect `linode-cli obj du` number formatting

- linodecli/__init__.py
- linodecli/arg_helpers.py
- linodecli/output.py
- tests/unit/test_output.py
This PR adds a new option, `--ascii-table`, to display output like this:
This is better than the default (unicode) tables in some CI runners. It may be more visually appealing to some users as well.
**Questions for consideration:** 
- Should this be an output option, or a global config/setting? 
- An advantage of a global setting is users may prefer to see ALL tables (including "Available Commands, etc") in this style, as opposed to just output. 
- What do you think of the option name? 
- `--ascii` is cleaner and more consistent with existing `json` and `markdown` options, but I thought it'd be better to explicitly call out that this applies to the tables only (e.g. not any data coming back from the API).
- Try out the new `--ascii-table` option
- Run the new unit test: `pytest …
> feat: option to display output in ASCII tables

- linodecli/output.py
- tests/unit/test_output.py
This change fixes a bug that would cause an error to be raised when attempting to disable truncation on certain commands.
```bash
make testunit
```
```bash
make install
linode-cli linodes ls --no-truncation
```
> fix: Resolve type error when using `--no-truncation` on non-string values

- linodecli/api_request.py
- linodecli/baked/operation.py
- linodecli/baked/request.py
- tests/fixtures/api_request_test_foobar_post.yaml
- tests/unit/test_api_request.py
- tests/unit/test_operation.py
This change allows users to specify `null` as a value for fields that are marked as `nullable` in the API spec. This is useful for situations where the API may have certain functionality tied to having a certain value be explicitly `null` (e.g. RDNS resets)
e.g.
```bash
linode-cli networking ip-update --rdns null 127.0.0.1
```
**NOTE: This will need to be partially reworked after the spec parser refactor, but the change should be relatively straightforward.**
Resolves #266 
```
make testunit
```
> new: Add support for explicit nullable arguments

- linodecli/api_request.py
- linodecli/arg_helpers.py
- linodecli/baked/operation.py
Changes `--order_by`flag to `--order-by` to match CLI conventions. Also added a print statements for `--help` for list actions.
`linode-cli linodes list --order-by label`
`linode-cli linodes list --help`
> Fix: changing `--order_by` to `--order-by` to match CLI flag conventions

- linodecli/baked/response.py
- linodecli/output.py
This change resolves an issue that caused the `x-linode-cli-rows` spec extension to not work as expected, which caused the `linodes backups-list {instanceId}` to be unusable.
Fixed command:
```bash
linode-cli linodes backups-list 12345
```
Integration tests:
```bash
make RUN_LONG_TESTS=TRUE testint
```
> fix: Resolve issue with `x-linode-cli-rows` extension

- linodecli/baked/request.py
- tests/integration/stackscripts/test_stackscripts.py
This change resolves an issue that caused `object` request fields without properties in the OpenAPI spec to not be handled as JSON arguments. This mirrors the functionality present in the old spec parser implementation 
Integration Tests:
```
make INTEGRATION_TEST_PATH="stackscripts" testint
```
Manually:
```
linode-cli linodes create --stackscript_data '{"foo": "bar"}' ...
```
> fix: Resolve issue with creating arguments for objects without properties

- linodecli/output.py
- tests/unit/test_output.py
This PR updates the table output logic to display the full path of nested fields in their column headers. Additionally, this change allows users to format on nested fields using their full paths (e.g. `linode-cli events ls --format entity.id`).
```
make testunit
```
> proposal: Display full path in the header for nested columns

- .github/workflows/e2e-suite.yml
removed -m argument when running integration test in e2e-suite.yml, this was causing all tests to be skipped.
Added extra step to set the file name correctly after test execution
> fix: e2e-suite.yml typo in pytest and set file name properly

- linodecli/output.py
- tests/integration/firewalls/test_firewalls_rules.py
This change disables the maximum depth limit for attributes when using the `--json` output mode. This depth limit is enforced for tables to prevent nested list fields from being displayed under a non-nested table, but JSON outputs aren't subject to the same limitation.
```
make testunit
make INTEGRATION_TEST_PATH=firewalls/test_firewalls_rules.py testint
```
> fix: Disable attribute depth limit for JSON outputs

- linodecli/output.py
- tests/integration/firewalls/test_firewalls_rules.py
This change resolves an issue that would cause an error when attempting to format on nested list fields in `--json` mode.
```
make testunit
make INTEGRATION_TEST_PATH=firewalls/test_firewalls_rules.py testint
```
> fix: Resolve issue with formatting on nested fields in JSON mode

- tests/integration/events/test_events.py
- tests/integration/image/test_plugin_image_upload.py
- tests/integration/tags/test_tags.py
- skip failing test due to bug - "https://github.com/linode/linode-cli/issues/500"
-  add teardown method at end of tags test suite
-  edit assertion for image upload test
> test: fix/skip integration test failures

- linodecli/api_request.py
- linodecli/configuration/__init__.py
- tests/unit/conftest.py
- tests/unit/test_api_request.py
- tests/unit/test_configuration.py
Removing dbaas configuraiton steps as dbaas is now opt-in only.
`pytest -v tests/unit/test_configuration.py`
> fix: remove dbaas configuration

- linodecli/output.py
This change updates the JSON `--format` logic to support outputting empty lists that meet the format criteria.
```
make testunit
```
> fix: Display empty lists when using `--json`

- .github/workflows/e2e-suite.yml
- tests/integration/cli/test_help.py
Failing integration tests currently does not mark the run as 'x' (failed). Hence adding logic to mark it as failed when there are failures
> Fix: mark execution as failed when there are failures

- .pylintrc
- linodecli/__init__.py
- setup.py
`pkg_resources` was deprecated and removed in Python 3.12.
You can insert a `print(VERSION)` to right after where the `VERSION` is defined. Then run any command with the Linode CLI, and you will be able to see the output.
> Drop Python 3.7 Support and Remove Usage of `pkg_resources`

- linodecli/plugins/region-table.py
Change `Firewalls` to `Cloud Firewall` which is the correct term used in the API.
Remove `Block Storage Migration` from the table.
Rename `Blocks` to `Block`
Resolves #532
> fix: `region-table` Firewall column

- Makefile
- linodecli/baked/operation.py
- linodecli/baked/response.py
The existing CLI code doesn't work with network interface listing API from the VPC OpenAPI spec draft.
1. Install CLI with VPC OpenAPI spec draft, 
```bash
SPEC=https://raw.githubusercontent.com/bbiggerr/linode-api-docs/add/vpc/openapi.yaml make install
```
2. [Config the CLI](https://github.com/linode/linode-cli/wiki/Configuration#configurable-api-url) to target alpha API server. (Ping me if you would like to know how to do it in details)
3. Create a Linode on alpha and try to list the network interfaces in its config with the CLI:
```bash
linode linodes config-interfaces-list [LINODEID] [CONFIGID]
```
Expected result looks like:
```
┌───────┬───────┬─────────┬──────────────┐
│ id    │ label │ purpose │ ipam_address │
├───────┼───────┼─────────┼──────────────┤
│ 12345 │       │ public  │ …
```
> Support VPC Interfaces Changes

- .github/workflows/e2e-suite.yml
- linodecli/overrides.py
- tests/unit/test_overrides.py
Add `region_prices` as an extra column in the linode types table to show user DC-specific pricing of each linode type.
Unit test: `make testunit`
Manual test: run command `linode-cli linodes types`
Old table:
New table:
> new: Display region_prices in linode types output

- .github/workflows/e2e-suite-pr.yml
- Correct the example in the description `test_path` parameter of the [run e2e test workflow](https://github.com/linode/linode-cli/actions/workflows/e2e-suite-pr.yml).
- Add GitHub Token to the graphql API call (for checking the commit has of a PR).
- Bump repo checkout action version.
- Cleanup unnecessary step, `Install system deps`
> Fix run e2e workflow

- linodecli/plugins/obj/objects.py
We imported boto3 in `objects.py` which skips the boto3 check logic `__init__.py`. Added `try ... except ...` block to ignore the exception and let the `call` function in `__init__.py` to print the error message.
`make install`
`python3 -m pip uninstall boto3 -y`
`linode obj ls`
GHA run passed: https://github.com/linode/linode-cli/actions/runs/6750190271
> Fix `boto3` missing error message in obj extension

- pyproject.toml
- requirements-dev.txt
- version
`distutils` has been removed in Python 3.12, and we need to replace it with `packaging` in order to get the release workflow works again.
This is targeting `dev` branch intentionally because other code in `dev` branch is needed to get everything working with Python 3.12.
1. Install both Python 3.11 and 3.12.
2. `export LINODE_CLI_VERSION=v1.2.3.dev` 
OR
`export LINODE_CLI_VERSION=v1.2.3`
4. Then these three ways should output the same result of version. 
`python3.12 version`
`python3.11 version`
`python3.11 version` (in main branch before merging this PR)
> Replace `distutils` with `packaging` for Py 3.12

- linodecli/overrides.py
Some of our statically typed function params in the CLI uses dict[...] rather than Dict[...], which is supported in later Python versions but not in 3.8. This PR updates this accordingly to allow Python 3.8 users to make use of the CLI.
In a Python 3.8 (see [pyenv](https://github.com/pyenv/pyenv)):
1. `make install`
2. Validate the CLI in PATH is in your Python 3.8 environment (`which linode-cli`)
3. `linode-cli linodes types`
> fix: `dict[...]` -> `Dict[...]` for Python 3.8 compatibility

- .github/workflows/remote-release-trigger.yml
This change updates the automated release workflow to create release tags on the main branch rather than the default (dev) branch. This is necessary because we only want to release code that has been merged to the main branch.
Example run: https://github.com/lgarber-akamai/linode-cli/actions/runs/6814710635
> fix: Use HEAD SHA from main branch rather than default branch

- .github/workflows/e2e-suite.yml
- scripts/add_to_xml_test_report.py
- tests/integration/cli/test_help.py
Problem: For some context, the script that is used to upload test report from OBJ storage to TOD is currently calling GitHub API endpoints from ECP Test VM to get the release info for corresponding repository. However recently there has been a rate limiting issue that is causing an error calling endpoint from that particular VM. E.g.
`Error: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/linode/terraform-provider-linode/releases/latest
linode-terraform None`
Fix: Use existing add_to_xml_report.py script to add the release information to the xml report before uploading it to Object Storage so we don't have to rely on calling any endpoints from the Test VM
Build - 
**If applicable, include a screenshot or …
> test: add release info to xml file before uploading to obj storage

- linodecli/plugins/obj/__init__.py
- tests/unit/test_plugin_obj.py
When using the command with a invalid region it would print out a large stack trace error, to fix this I added a list of valid clusters generated from the API.
Use the command with a invalid cluster ID
```bash
lin obj --cluster us-west
```
> fix: obj plugin error with invalid cluster

- linodecli/arg_helpers.py
Creates a clickable (if supported) hyperlink for `--help` output.
Run a help command and click the link or observe its style change.
```bash
make install
lin linodes ls --help
```
> new: hyperlinks for help URLs

- linodecli/plugins/image-upload.py
- tests/integration/image/test_plugin_image_upload.py
This change adds a `--cloud-init` flag to the `image-upload` plugin, indicating that an image is cloud-init compatible.
Depends on: https://github.com/linode/linode-api-docs/pull/893
Resolves #556 
The following test steps assume you have pulled down this change and ran the following:
```bash
make SPEC="https://raw.githubusercontent.com/linode/linode-api-docs/93b217f629d821ddb6bd8c52c341104e793c9885/openapi.yaml" install
```
```bash
make INTEGRATION_TEST_PATH=image testint
```
1. Create an arbitrary gzipped image.
```bash
touch test_image && gzip test_image
```
2. Upload the image to Linode with the cloud-init flag specified. Take note of the returned image ID.
```bash
linode-cli image-upload --label test-image --region us-iad --cloud-init test_image.gz
```
3. Once the image has been …
> new: Add `--cloud-init` flag to image upload plugin

- linodecli/plugins/metadata.py
- requirements.txt
- tests/unit/test_plugin_metadata.py
This PR adds a plug-in to the CLI that allows users to use the Metadata Service API easily. Note: This plug-in will not be functional until py-metadata is publicly available.
**Running Unit Tests**
Note: No tests will be functional _unless_ py-metadata is installed on your machine.
**Manual Testing**
1. Enter Linode instance named _amisiorek-metadata-cli_ as linodedx user using SSH key (if not authorized, message me and I will add your key)
2. Run `source venv/bin/activate` to enter venv
3. Run the following commands to see the plug-in in action:
`linode-cli metadata instance`
`linode-cli metadata sshkeys`
`linode-cli metadata networking`
`linode-cli metadata user-data`
`linode-cli metadata --help`
> Creating Metadata Plugin

- linodecli/configuration/__init__.py
Change string concatenation style to be adjacent string literal for improved code readability.
Set your Linode token into env var called `LINODE_CLI_TOKEN`, and then run `linode configure`, and verify the string is displayed correctly.
> Change string concatenation style to be adjacent string literal

- tests/integration/account/test_account_transfer.py
- tests/integration/linodes/test_types.py
Added the test for
linode-cli linodes types
linode-cli account transfer
What does this PR do and why is this change necessary?
covers the integration test
✔️ How to Test
Run test individually
make INTEGRATION_TEST_PATH=/linodes/test_types.py testint
make INTEGRATION_TEST_PATH=account testint
Run all test
make testint
> added test for linode_type and account_transfer 

- linodecli/arg_helpers.py
- linodecli/baked/operation.py
- requirements-dev.txt
- tests/unit/test_arg_helpers.py
This pull request adds a new `Example Usage` section to generated command help pages. These examples are pulled from the `x-code-samples` OpenAPI spec extension.
This functionality was previously implemented before the spec parser rework (#299, #303) but was never merged. Thanks @bavedarnow and @Dorthu for the original idea and implementations!
Closes #299, #303 
The following testing instructions assume you have pulled down this change and run `make install`.
```bash
make testunit
```
1. View the help page for the `linodes create` (POST) command:
```bash
linode-cli linodes create --help
```
2. Observe the `Example Usage` section displays as expected.
3. View the help page for the `linodes view` (GET) command:
```bash
linode-cli linodes view --help
```
4. Observe the `Example Usage` …
> new: Display example usage in command help pages

- .github/workflows/publish-wiki.yml
Fixes the formatting of the workflow file, tested with ACT but unfortunately secrets dont work so well in ACT, I'm getting the same response I get from remote-release-trigger though so it seems to be progressing past my error now.
```bash
act -j publish-wiki
```
> fix: wiki publishing gha

- linodecli/baked/operation.py
- tests/fixtures/api_request_test_foobar_post.yaml
- tests/unit/test_operation.py
This change resolves an issue that caused some object list entries to not be processed when some keys are excluded. 
```bash
make testunit
```
1. Pull down this change.
2. Install the Linode CLI:
```bash
make install
```
3. Create an arbitrary VPC and subnet:
```bash
export VPC_ID=$(linode-cli vpcs create --label test-vpc --region us-mia --json | jq '.[0].id')
export SUBNET_ID=$(linode-cli vpcs subnet-create --label test-subnet --ipv4 '10.0.1.0/24' ${VPC_ID} --json | jq '.[0].id')
```
4. Attempt to create a Linode with a VPC and public interface using debug mode:
```bash
linode-cli linodes create \
--label test-instance \
--region us-mia \
--image linode/alpine3.19 \
--root_pass 'testp4ssw0rd!!!!!!23123' \
--type g6-nanode-1 \
--interfaces.primary true --interfaces.purpose vpc …
```
> fix: Resolve issue when not specifying all keys for object list entries

- linodecli/baked/operation.py
- linodecli/baked/request.py
- tests/fixtures/api_request_test_foobar_post.yaml
- tests/integration/conftest.py
- tests/integration/linodes/test_interfaces.py
- tests/integration/vpc/conftest.py
- tests/unit/test_operation.py
This change resolves an issue that caused nested dict fields in object lists (e.g. `--interfaces.ipv4.nat_1_1`) to be excluded from request bodies.
This issue occurred because the logic to traverse API spec request arguments did not preserve whether a nested dict field was under a list. Additionally, the name of the list for a field was resolved using the prefix of a field rather than its top-level list name causing mismatches for deeply nested fields.
The following test steps assume you have pulled down this change locally and run `make install`.
```bash
make INTEGRATION_TEST_PATH=linodes/test_interfaces.py testint
```
```bash
make testunit
```
1. Create an arbitrary VPC and VPC subnet:
```bash
export VPC_ID=$(linode-cli vpcs create --label test-vpc --region us-mia --json | jq '.[0].id') …
```
> fix: Resolve bug that prevented nested dict fields in object lists from being included in request body

- tests/integration/vpc/test_vpc.py
Due to the API schema change,  `linodes` column is no longer shown in CLI text mode output. Removing it in this PR
`make INTEGRATION_TEST_PATH="vpc" testint`
> Fix vpc tests by removing `linodes` column

- linodecli/api_request.py
- linodecli/baked/operation.py
- tests/fixtures/api_request_test_foobar_post.yaml
- tests/unit/test_api_request.py
- tests/unit/test_operation.py
This change resolves a few minor bugs related to how explicit list values (`[]`) and explicit null values (`null`) are serialized in request bodies when nested in a list.
The resolved issues are as follows:
- Explicit null values nested in object lists raised an `Object of type ExplicitNullValue is not JSON serializable` error
- Implicit null values were not automatically excluded from list objects
This PR specifically adds a new `_traverse_request_body` function that drops implicit null values and replaces ExplicitNullValue and ExplicitEmptyListValue with `None` and `[]` respectively.
The following test steps all assume you have pulled down this code locally and run `make install`.
```bash
make testunit
```
```bash
make testint
```
1. Run the following CLI command to create an instance …
> fix: Resolve issues with nested explicit list and null value serialization

- linodecli/arg_helpers.py
- linodecli/baked/request.py
- tests/fixtures/api_request_test_foobar_post.yaml
- tests/integration/linodes/test_interfaces.py
- tests/unit/test_arg_helpers.py
- tests/unit/test_operation.py
This change allows users to specify deeply nested array fields (e.g. `--interfaces.ip_ranges`) as JSON. These fields previously could not be specified at all due to limitations with how the CLI differentiates between objects in complex lists.
This PR also adds a new suffix for fields on command help pages that identifies whether an argument expects JSON.
**NOTE: The failing metadata plugin unit tests are not relevant to this PR and can be ignored, see TPT-2691.**
The following test steps assume you have pulled down this change locally and run `make install`.
```bash
make INTEGRATION_TEST_PATH=linodes/test_interfaces.py testint
```
```bash
make testunit
```
1. Create a VPC and VPC subnet:
```bash
export VPC_ID=$(linode-cli vpcs create --label test-vpc --region us-mia --json | jq '.[0].id') …
```
> fix: Support specifying arrays nested in complex lists as JSON

- linodecli/plugins/metadata.py
- tests/unit/test_plugin_metadata.py
This change addresses a breaking change in the `metadata` plugin that caused the `sshkeys` command to raise an error. This breaking change was made in the Metadata SDK because the MDS can resolve the SSH keys of users configured using cloud-config and we are no longer limited to the root user.
To simply the formatting a bit, each row in the command output now represents a single key/user relationship.
The following test steps assume you are on a development Linode, have pulled down this change, and have run `make install`.
```
make testunit
```
1. Run the following:
```
linode-cli metadata sshkeys
```
2. Ensure the output is similar to the preview below.
> new: Address breaking change in MDS plugin `sshkeys` command

- Makefile
This is to allow baking being skipped during `make build` or `make install`
- Run `make build` to verified `bake` runs (`python3 -m linodecli bake` in the standard output)
- Run `SKIP_BAKE=1 make build` to verify `bake` doesn't run (`Skipping bake stage` in the standard output)
> Add `SKIP_BAKE` Argument to `bake` Target in Makefile

- linodecli/api_request.py
- linodecli/cli.py
- linodecli/plugins/metadata.py
- tests/unit/conftest.py
- tests/unit/test_api_request.py
- tests/unit/test_cli.py
This change updates the API request User-Agent to include the version of the API spec and updates the `metadata` plugin to include the CLI User-Agent in its requests.
Expected UA for generated CLI commands:
```
linode-cli/0.0.0 linode-api-docs/4.173.0 python/3.12.1
```
Expected UA for `metadata` plugin commands:
```
linode-cli/0.0.0 linode-api-docs/4.173.0 python/3.12.1 linode-py-metadata/0.2.0
```
The following test steps assume you have pulled this PR locally and run `make install`.
```
make testunit
```
**NOTE: These instructions do not include steps for testing the metadata plugin UA because the metadata SDK does not yet support debug outputs (see https://github.com/linode/py-metadata/pull/29).**
1. Run the following command:
```bash
linode-cli linodes ls --debug
```
2. Ensure the …
> new: Add API spec version to User-Agent; add User-Agent to metadata plugin requests

- linodecli/plugins/obj/__init__.py
- linodecli/plugins/obj/helpers.py
- linodecli/plugins/obj/list.py
- tests/integration/obj/test_obj_plugin.py
This is to move some functions of the obj plugin from `__init__.py` to its own file.
```bash
make testint INTEGRATION_TEST_PATH=obj
```
```bash
linode obj la --cluster us-mia-1
linode obj ls --cluster us-mia-1
linode obj ls YOUR_BUCKET_NAME --cluster us-mia-1
```
> Move listing functions of the obj plugin to its own files

- .github/labels.yml
- .github/workflows/labeler.yml
Updates to use githubs built in release notes and using the following labels.
`**NOTE**: The labeler job is dry running on the PR to show what it will do, doesn't execute until we merge.`
breaking-change: any changes that break end users or downstream workflows
bugfix: changes that fix a existing bug
new-feature: changes that add new features such as endpoints or tools
improvement: changes that improve existing features or reflect small API changes
testing: improvements to the testing workflows
repo-ci-improvement: improvements to the CI workflow, like this PR!
documentation: updates to the package/repo documentation or wiki
dependencies: Used by dependabot mostly
ignore-for-release: for PRs you dont want rendered in the …
> ci: update labels and release drafter

- Makefile
- tests/integration/conftest.py
- tests/integration/linodes/helpers_linodes.py
- tests/integration/linodes/test_backups.py
In this pull request, several improvements are made:
- outdated backup test is updated to reflect the requirement of setting `backups_enabled` in account settings before executing the backup test
-  usage of INTEGRATION_TEST_PATH is replaced with MODULE for better clarity when running tests against specific modules
- All warning messages in int/smoke tests are addressed
`make TEST_CASE="test_create_linode_with_backup_disabled" testint`
`make smoketest`
`make MODULE=account testint`
> test: Update outdated backup test and address test warnings messages 

- .github/workflows/e2e-suite.yml
- Makefile
Substitute hacky solution of executing integration tests and uploading test data with a more efficient solution using a conditional statement. This enhancement enables us to directly view test output within its associated step :)
Verified the workflow on forked - https://github.com/ykim-1/linode-cli/actions/runs/8976874220/job/24654595327
TOD link (test instance) - http://198.19.5.79:7272/builds/663969074f454e00016b8db6?team=DX&buildName=linode-cli%205.49.1&bld_id=663969074f454e00016b8db6
> CI: replace test execution handler with conditional

- tests/integration/cli/test_host_overrides.py
- tests/integration/linodes/test_backups.py
Adding skip to backup tests as `backups_enabled` setting does not apply to accounts that are managed
TOD Link - http://198.19.5.79:1212/tests?team=DX&buildName=linode-cli&bld_id=664babc93caad400014ecda6&testcaseName=test_create_linode_with_backup_disabled
1. Log into account that is managed (e.g. cli testing account)
2. ` make TEST_CASE="test_create_linode_with_backup_disabled" testint -s `
> test: Add skip for backup test for managed test accounts

- linodecli/plugins/obj/helpers.py
This change resolves an issue that caused the following error to be raised when attempting to render cells with an integer value in the OBJ plugin:
```
rich.errors.NotRenderableError: unable to render int; a string or other renderable object is required
```
The following test steps assume you have pulled down this PR and run `make install`.
```
make MODULE=obj testint
```
N/A
> fix: Resolve cell rendering error in OBJ plugin

- .github/workflows/e2e-suite-pr.yml
- tests/integration/conftest.py
- tests/integration/firewalls/test_firewalls.py
- tests/integration/linodes/helpers_linodes.py
- tests/integration/linodes/test_backups.py
- tests/integration/linodes/test_interfaces.py
- tests/integration/linodes/test_linodes.py
- tests/integration/linodes/test_power_status.py
- tests/integration/linodes/test_rebuild.py
- tests/integration/linodes/test_resize.py
- tests/integration/lke/test_clusters.py
- tests/integration/networking/test_networking.py
- tests/integration/nodebalancers/test_node_balancers.py
- tests/integration/ssh/test_plugin_ssh.py
- tests/integration/ssh/test_ssh.py
- tests/integration/support/test_support.py
This PR implements Linode Cloud Firewall for integration tests to enhance security. 
More info can be found in [Best Practices to keep VMs safe](https://docs.google.com/document/d/1XowpyiU09AfsXxtt1Jnmeev8W9o6GuwaShW7kK-zjlM/edit?parentUrl=https%3A%2F%2Fac-aloha.akamai.com%2Fhome%2Flinode-vm-best-practices%2Flinode-vm-best-practices&iframeId=b8819df3-0010-5c00-8d3a-26aa6d14b1a5#heading=h.r7cjnl29apd1).
Note: GHA does not support ipv6 so only ipv4 will get added in firewall during GHA execution. However, ipv6 will get added automatically if ipv6 address and route exist
`make testint`
https://github.com/linode/linode-cli/actions/runs/9217506829
> test: Add Linode Cloud Firewall for all test linode instances

- linodecli/plugins/obj/__init__.py
- tests/unit/test_plugin_obj.py
The upcoming MultiCluster OBJ service will introduce multiple clusters per region, and clusters list API will be deprecated.
Removing clusters list when doing `linode obj configure` and change it to a text input.
```
pytest tests/integration/obj
```
```bash
make testunit
```
```bash
linode obj configure
```
Then type any cluster you want:
```
(venv) myusername@mylaptop linode-cli % linode obj configure
Configure a default Cluster for operations. (Optional): us-mia-1
```
Or leave it blank:
```
(venv) myusername@mylaptop linode-cli % linode obj configure
Configure a default Cluster for operations. (Optional):
```
And then try any obj plugin commands, for examples:
```
linode obj la
```
```
linode obj la --cluster us-east-1
```
> Change Clusters Choice in OBJ Plugin Config to be Text Input

- .github/workflows/e2e-suite.yml
- scripts/lke-policy.yaml
- scripts/lke_calico_rules_e2e.sh
- tests/integration/lke/test_clusters.py
A new script, `lke_calico_rules_e2e.sh`, has been added and is called in the E2E workflow file after the `Run the integration test suite step` in `e2e-suite.yml`
Key Points:
- `kubectl` and `calicoctl` binaries are required as pre-req which are downloed in the e2e worflow file
- The script retrieves all LKE clusters in the test account and applies Calico rules to the corresponding nodes. If no clusters exist, no action is taken. In most cases, clusters are cleaned and deleted properly after test execution
- Due to the delay in the availability of LKE cluster configurations and the provisioning times of node instances, it is challenging to apply Calico rules directly within the test framework. Therefore, the script is separated and executed independently in the workflow file
PR has been …
> test: Add Calico Inbound and Outbound policies to LKE nodes for E2E

- .github/workflows/e2e-suite.yml
- .github/workflows/nightly-smoke-tests.yml
This PR adds option to run integration tests against minimal test account in `e2e-suite.yml` workflow
Forked Run with specified SHA - https://github.com/ykim-1/linode-cli/actions/runs/9668566683
Forked Run merged to dev - https://github.com/ykim-1/linode-cli/actions/runs/9669162821
> test: Add option to run integration tests against minimal test account without any special customer tags

- tests/integration/cli/test_host_overrides.py
- tests/integration/helpers.py
- tests/integration/image/test_plugin_image_upload.py
Fixed integration tests that were failing due to changes in exit codes across the project.
`make testint`
NOTE: The following integration tests are failing for reasons unrelated to exit codes
- tests/integration/account/test_account.py::test_user_view
- tests/integration/support/test_support.py::test_tickets_view
- tests/integration/support/test_support.py::test_view_replies_support_ticket
> Fixed exit code related integration tests

- linodecli/plugins/obj/__init__.py
- linodecli/plugins/obj/buckets.py
- linodecli/plugins/obj/helpers.py
- tests/integration/obj/test_obj_plugin.py
- Fixed issues:
- A `ClientError` happens in the S3 client doesn't have any error message output
- Versioned buckets containing objects can't be deleted recursively
- Buckets containing more than 1000 objects can't be deleted recursively
```bash
pytest tests/integration/obj/test_obj_plugin.py -k "test_large_number_of_files_single_bucket"
```
You can create these objects and buckets with OpenTofu/Terraform, but they will run for a very long time to create 2010 objects.
```bash
tofu apply -parallelism=100
```
```terraform
provider "linode" {
obj_bucket_force_delete = true
}
resource "linode_object_storage_bucket" "nonversioned-bucket" {
region = "us-mia"
label  = "test-cli-recursive-rb1"
}
resource "linode_object_storage_bucket" "versioned-bucket" {
region = "us-mia"
label  = …
```
> Add Paginator to Recursively Delete All Objects Before Delete Bucket

- linodecli/api_request.py
- linodecli/configuration/config.py
- tests/unit/test_configuration.py
- wiki/Configuration.md
Adds `get_bool('value')` method for configuration options and adds a step in configuration to support `suppress-version-warning`.
Also adds support for `LINODE_CLI_SUPPRESS_VERSION_WARNING` environment variable.
1. Install the new version of the CLI
```bash
make install
```
2. Go through the configuration process
```bash
lin configure
```
3. The last question should ask you about suppressing API Version Warnings
4. Use the CLI and see if you view this warning
1. Install the new CLI or delete the value from your config
2. Use the cli after setting the environment variable
```bash
export LINODE_CLI_SUPPRESS_VERSION_WARNING=true
lin linodes ls
unset …
```
> Add suppress-version-warning config option

- linodecli/__init__.py
- linodecli/help_pages.py
- tests/unit/conftest.py
- tests/unit/test_help_pages.py
This pull request breaks the CLI command help page logic out into a separate function and implements the logic to sort action entries by name. This should improve the readability of certain groups since the order of actions in the spec is not guaranteed to be readable.
Additionally, this PR adds a new test case to validate the output of this help page.
The following test steps expect you have pulled down this PR and run `make install`.
```shell
make testunit
```
1. View the help page for a single CLI command/group:
```shell
linode-cli networking --help
```
2. Ensure all printed actions are sorted by name.
> new: Break out command help page logic; sort actions in output

- tests/integration/volumes/test_volumes.py
- tests/integration/volumes/test_volumes_resize.py
Recently resize limits have been changed. E.g. 10240GB to 16384GB. This PR addresses this change in assertions and also fix failures related to "unique label" 
make MODULE="volumes" testint
> test: Update volume tests to reflect new threshold values for sizing

- pyproject.toml
- tests/integration/linodes/test_power_status.py
- tests/integration/linodes/test_rebuild.py
- tests/integration/linodes/test_resize.py
- tests/integration/lke/test_clusters.py
Following list of tests failed occasionally in recent builds, refer to TOD for details.
- test_rebuild_fails_without_image 
- test_resize_fails_to_the_same_plan 
- test_list_kubernetes_endpoint 
- test_shutdown_linode
This PR uses existing pytest library called pytest-rerunfailures to rerun tests with delay. Flaky tests now can simply be marked with
`@pytest.mark.flaky(reruns=3, reruns_delay=2)`
> test: Add retry on flaky tests

- Makefile
- linodecli/api_request.py
Running unit tests caused existing config in `~/.config/linode-cli` to be overwritten, this PR fixes this issue by setting the environment variable prior to the test execution so the config file will get written in temporary location. After the execution the environment variable will be reverted to original value.
1. unset `LINODE_CLI_TOKEN`
2. `make install`
3. `linode-cli linodes ls` - Expected to fail
4. `make testunit`
5. verify ~/.config/linode-cli is not overwritten
> test: fix unit tests to not overwrite existing cli config file

- .github/workflows/e2e-suite.yml
Needed to use job status instead of step outcome
e.g.
```
"text": "*Build Result:*\n${{ steps.integration_tests.outcome == 'success' && ':large_green_circle: Build Passed' || ':red_circle: Build Failed' }}"
```
Instead need to use,
```
"text": "*Build Result:*\n${{ needs.integration_tests.result == 'success' && ':large_green_circle: Build Passed' || ':red_circle: Build Failed' }}"
```
Tested on forked repo - https://github.com/ykim-1/linodego/actions/runs/11075403223
> test: Fix slack payload in integration workflow

- linodecli/overrides.py
Override `images replicate` output to leverage `replicas`. Also improve the table format and make it more readable.
1. Pull this PR and install this change:
```
make install
```
2. Replicate an existing image to some regions, i.e.:
```
linode images replicate private/123456 --regions us-iad --regions us-ord --regions us-east
```
3. Observe the command works successfully and the output looks good. An example output:
> Override images replicate output

- linodecli/plugins/get-kubeconfig.py
- tests/unit/test_plugin_kubeconfig.py
This PR fixes the plugin `get-kubeconfig` merging a Kubeconfig from the Linode API with a local kubeconfig file, in the case that all other clusters, contexts, or users have been discarded before. The problem can occur because standard kubeconfig editing tools (e.g. `kubectl config`) set the list entries to `null` instead of an empty list `[]`.
Also the output when adding the `--dry-run` parameter is now showing YAML output (i.e. the expected Kubeconfig update after running the command) instead of a Python dict.
1. From an existing Kubeconfig file, remove all contexts using `kubectl config delete-context <context_name>`.
2. Note that the value in this Kubeconfig file now contains a root level value `contexts: null` instead of `contexts: []`.
3. Run `linode-cli get-kubeconfig --label …
> fix: get-kubeconfig merge into empty lists

- Makefile
- linodecli/configuration/config.py
- linodecli/configuration/helpers.py
- linodecli/help_pages.py
- tests/unit/test_configuration.py
- wiki/Configuration.md
- wiki/development/Development - Overview.md
User can specify a custom configuration path to replace the default one through a new environment variable `LINODE_CLI_CONFIG`. If this path does not exist yet, we'll create it inexplicably. 
Fixed a behavior change to allow config update look for DEFAULT section. 
```
make testunit
```
1. Pull this PR and install the change locally:
```
make install
```
2. Run the help topic and see the new environment variable is available in the list:
```
linode-cli env-var
```
3. Set a custom config path, i.e.:
```
export LINODE_CLI_CONFIG="~/.test-config/cli-config"
```
4. Reconfigure CLI:
```
linode-cli configure
```
5. Find the reconfigure finished successfully and configuration is written into the new file.
6. Run a command and observe that the allowed default values are used, i.e.: 
``` …
```
> new: Allow specifying a custom configuration path through environment variable

- linodecli/api_request.py
- tests/unit/test_api_request.py
Updated debug output to sanitize bearer token
Pull down this PR and run `make install`
After running `make install`, run any CLI command with the debug flag (i.e. `linode-cli firewalls list --debug`) and verify that the Bearer Token is sanitized in the output.
> Sanitize Bearer Token in debug output

- tests/integration/cli/test_help.py
New spec was causing help test cases to fail due to different amount of characters that were being wrapped in output, this PR increases the wrapped output length to account for the change.
`make TEST_CASE="test_help_page_for_aliased_actions" testint`
`make TEST_CASE="test_help_page_for_non_aliased_actions" testint `
> test: Update help menu test cases 

- .github/workflows/e2e-suite-windows.yml
- .github/workflows/e2e-suite.yml
- tests/integration/image/test_plugin_image_upload.py
- tests/integration/ssh/test_plugin_ssh.py
Improvements to e2e CI:
- Separated security steps in different jobs including: applying calico script, applying cfw to any remaining instances/nodes
- Changed `test_path` to `module` for simplicity
e.g. 
Test cases `test_invalid_file` and `test_ssh_instance_provisioning` are updated accordingly to reflect recent stderr change
`make TEST_CASE="test_invalid_file" testint`
`make TEST_CASE="test_ssh_instance_provisioning" testint`
Tested in forked - https://github.com/ykim-1/linode-cli/actions/runs/11506669904
note: failed cases are not related to this PR but verified the security steps after integration job is finished
> test: Separate applying calico rules to different job; add job to apply cfw after integration tests are executed; update test_invalid_file test case

- Makefile
- tests/unit/test_configuration.py
- tests/unit/test_plugin_image_upload.py
- tests/unit/test_plugin_ssh.py
Unit tests have been failing due to error output being routed to stderr instead of stdout introduced by this [PR](https://github.com/linode/linode-cli/pull/644)
The reason why it wasn't detected in  the workflow in the first place is because our makefile returned status of export command instead of actual exit code of pytest command. 
E.g. 
```
.PHONY: testunit
testunit:
@mkdir -p /tmp/linode/.config
@orig_xdg_config_home=$${XDG_CONFIG_HOME:-}; \
export LINODE_CLI_TEST_MODE=1 XDG_CONFIG_HOME=/tmp/linode/.config; \
pytest -v tests/unit; \
export XDG_CONFIG_HOME=$$orig_xdg_config_home;
```
This fix is also in this [PR](https://github.com/linode/linode-cli/pull/662)
> test: fix unit tests caused by error output being routed to stderr instead of stdout

- .github/dependabot.yml
This is to allow dependabot to check updates for GitHub Actions.
> Enable dependabot checking updates for GitHub Actions

- linodecli/baked/operation.py
- tests/fixtures/api_url_components_test.yaml
- tests/unit/test_operation.py
This pull request adds logic to account for an edge case where the apiVersion parameter exists but has no defined default, causing `OpenAPIOperation._resolve_api_version(...)` to fail. This error is occurring when building against a pre-release version of the OpenAPI spec.
```shell
make testunit
```
1. Manually bundle the Linode OpenAPI specification from the latest commit in the internal documentation repository.
2. Build and install the Linode CLI using the newly bundled spec:
```shell
make SPEC=/path/to/my/bundled/spec.json install
```
3. Ensure the CLI builds and installs successfully.
> Account for edge case where apiVersion param has no default

- tests/integration/helpers.py
- tests/integration/linodes/test_power_status.py
`test_reboot_linode` test has been failing intermittently quiet often. This PR implements some wait conditions and retry function to hopefully stabilize the test.
`make TEST_CASE="test_reboot_linode" testint`
> test: Improve flaky reboot instance test; Implement retry for execute test command function 

- linodecli/baked/operation.py
- linodecli/baked/parsing.py
- linodecli/baked/request.py
- tests/unit/test_parsing.py
This pull request resolves various issues that caused help page argument descriptions to not be properly parsed, leading to malformed outputs like:
```
--label (required): A unique.
```
```
make testunit
```
1. In your linode-cli project directory, create a new `dump_descriptions.py` file with the following contents:
```python
from linodecli import CLI
from rich.console import Console
from linodecli.baked.request import OpenAPIRequestArg
console = Console()
cli = CLI("0.0.0.dev", "https://localhost", skip_config=True)
cli.load_baked()
for op_name, op in cli.ops.items():
for action_name, action in op.items():
console.print(f"[green b]{op_name} {action_name}[/green b]: {action.summary}")
if …
```
> Improve parsing & formatting of help page descriptions

- linodecli/api_request.py
- linodecli/baked/operation.py
- tests/fixtures/api_request_test_foobar_put.yaml
- tests/integration/cli/test_help.py
- tests/unit/conftest.py
- tests/unit/test_api_request.py
This pull request fixes an issue where parameter values (e.g. `instanceId` for `/linode/instances/{instanceId}`) would be included in the request body in addition to being used to build the request's URL. This doesn't seem to cause issues on most endpoints but is causing some validation issues against certain DBaaS 2.0 endpoints.
```
make testunit
```
1. Run the following command (NOTE: This is expected to fail because the instance does not exist)
```shell
linode-cli linodes update --label foobar 12345 --debug
```
2. In the debug output, ensure the request URL matches `PUT https://api.linode.com/v4/linode/instances/12345` and the request body does _not_ contain the `linodeId` key.
> Exclude parameter values from API request bodies

- tests/integration/linodes/test_disk.py
- tests/integration/ssh/test_plugin_ssh.py
- tests/integration/vlans/test_vlans.py
This PR address failures in latest CLI integration test runs: 
- Test image  `linode/alpine3.16` is not available anymore hence updating the test image in SSH tests
- VLAN help message changed slightly so assertion was updated
`make MODULE="ssh" testint`
`make TEST_CASE="test_list_vlans_help_menu -v" testint`
> test: Update SSH and VLAN test cases

- pyproject.toml
- tests/unit/test_api_request.py
- tests/unit/test_overrides.py
Python 3.8 has been EOL, upgrade minimal Python version to 3.9 so we can use the features added in 3.9.
> Bump minimal Python version to 3.9

- linodecli/plugins/obj/objects.py
- tests/integration/obj/test_obj_plugin.py
This PR fixes the issue described in #685.
It replaces the existing `lstrip` call to extract the object prefix with a substring based on the length of the bucket name.
Tested full objects module and new test case which tries to reproduce the case described in #685.
* `make MODULE=obj testint`
* `make MODULE=obj TEST_CASE=test_obj_single_file_single_bucket_with_prefix_ltrim testint`
> Replace lstrip with substring to resolve #685

- linodecli/api_request.py
- tests/unit/test_api_request.py
Updated response debug output to include body.
Pull down this PR and run `make install`.
After running make install, run any CLI command with the debug flag (i.e. `linode-cli firewalls list --debug`) and verify that the response body is printed.
> Response bodies included in debug output

- linodecli/baked/response.py
- tests/fixtures/response_test_get.yaml
- tests/unit/test_response.py
This pull request updates the OpenAPI spec baking logic to properly response dictionaries as defined in the [OpenAPI 3 documentation](https://swagger.io/docs/specification/v3_0/data-models/dictionaries/).
This is necessary to support an upcoming change to the LKE Node Pool `labels` field.
```
make testunit
```
> Support dictionary values in API responses

- linodecli/api_request.py
- tests/unit/test_api_request.py
This pull request updates the filter generation logic to only use `+and` when necessary, which should reduce the impact of bugs when filtering on special-case fields (e.g. `entity.type`, `entity.id`). 
```
make testunit
```
1. Run the following command to create an instance with label `foobar` and tags `foobar` and `barfoo`:
```bash
linode-cli linodes create --type g6-nanode-1 --region us-mia --label foobar --tags foobar --tags barfoo
```
2. Run the following command to list instances matching the above conditions:
```bash
linode-cli linodes ls --label foobar --tags foobar --tags barfoo --debug
```
3. Ensure the debug output contains the following filter JSON:
```bash
X-Filter: {"label": "foobar", …
```
> Only use +and in filters when necessary

- linodecli/baked/operation.py
- linodecli/baked/request.py
- linodecli/baked/response.py
- linodecli/baked/util.py
- linodecli/help_pages.py
- tests/fixtures/operation_with_one_ofs.yaml
- tests/unit/conftest.py
- tests/unit/test_help_pages.py
- tests/unit/test_request.py
- tests/unit/test_response.py
This pull request adds support for parsing [OpenAPI oneOfs and anyOfs](https://swagger.io/docs/specification/v3_0/data-models/oneof-anyof-allof-not/) in both the request and response schema for operations. 
Additionally, this PR adds support for rendering each root-level request oneOf separate section in the generated command help pages.
The following test steps assume you have pulled down this pull request locally and run the following command:
```shell
make SPEC='https://gist.githubusercontent.com/lgarber-akamai/07485a643e8329a5c16bec775e8066c4/raw/56f4491ba6e239c9cad736f05ff2d1ab0608098c/openapi.json' install
```
**NOTE: The overridden specification is necessary because the currently published OpenAPI specification does not yet make use of oneOfs.**
```
make testunit
```
```
make …
```
> Support oneOfs & anyOfs in operation request & response schema

- linodecli/configuration/config.py
When configuring linode-cli, options are presented to the user in a random order. For example:
```
Select the user that should be given default SSH access to new Linodes.  Choices are:
1 - dour
2 - shiff
3 - retardment
4 - linotype
5 - subak
6 - frothy
7 - heptateuch
8 - sapp
9 - magisterial
10 - anglin
11 - fancied
12 - mercola
13 - naked
14 - aftershock
15 - spleen
16 - cuda
17 - carlinecarling
18 - natalienatalina
19 - whitehead
20 - rutherfordium
21 - sterrett
22 - integrated
23 - metacenter
24 - galegalea
25 - monachism
26 - turkish
27 - fabricate
28 - orvil
29 - rooker
30 - mintun
31 - prove
Default Option (Optional):
```
Have fun finding the user you're looking for!
This PR sorts the usernames to improve UX. It also sorts the regions, linode types, and images for the same reason.
I …
> Alphabetize config

- pyproject.toml
The [latest code change](https://github.com/linode/linode-cli/pull/718) in the CLI for supporting boto3 >= 1.36 is not compatible with boto3 <= 1.35.
```bash
make install && pytest tests/integration/obj/test_obj_plugin.py
```
> Requiring boto3>=1.36

- resolve_spec_url
This pull request re-points the default OpenAPI specification URL from
```
https://raw.githubusercontent.com/linode/linode-api-docs/.../openapi.yaml
``` 
to
```
https://raw.githubusercontent.com/linode/linode-api-docs/.../openapi.json
```
in response to the corresponding change in the linode-api-docs repository.
1. Run an arbitrary command using the new Linode CLI install.
```
make test-int
```
> Consume linode-api-docs/openapi.json rather than openapi.yaml

- linodecli/configuration/config.py
This is to fix an issue that prevent OBJ plugin to work when no default user has been configured to the CLI.
1. Remove existing CLI configuration file: `rm ~/.config/linode-cli` (if you have important stuff in the config, please back it up rather than remove)
2. Configure CLI via environmental variables.
```bash
export LINODE_CLI_TOKEN=[YOUR_API_TOKEN]
export LINODE_CLI_OBJ_ACCESS_KEY=[YOUR_OBJ_ACCESS_KEY]
export LINODE_CLI_OBJ_SECRET_KEY=[YOUR_OBJ_SECRET_KEY]
```
3. Verify the OBJ plugin is still working: `linode obj la`
> Fix failure on OBJ plugin when CLI is not configured

- Dockerfile
Updated dockerfile to python 3.12, removed cache from pip3 to reduce size of the docker image
Updated dockerfile to python 3.12, removed cache from pip3 to reduce size of the docker image
> Updated dockerfile to python 3.13, removed cache from pip3 to reduce size of the docker image

- linodecli/baked/request.py
- linodecli/baked/response.py
Improve the maintainability of baked/request.py and baked/response.py. Added/improved docstrings for all functions, methods, classes. Use static typing wherever possible. Added Inline comments for some confusing logics.
> ref: Improve maintainability for baked request and response

- wiki/_Sidebar.md
Adds a basic uninstallation document to remind users to remove the config file.
> Uninstall Document

- linodecli/configuration/config.py
- linodecli/configuration/helpers.py
Refactor the logic for handling absent of the config values by providing a fallback value in the `get` function call to replace the explicit checking with if statement.
There should not be any functionality change in this PR, but you can try various stuff with the CLI, for example:
1. `linode configure`
2. `linode linodes list`
3. ...
> Add fallback value to replace explicitly option checking for config gets

- wiki/Uninstallation.md
- wiki/_Sidebar.md
> Add Uninstall Document

- linodecli/plugins/ssh.py
- tests/unit/test_plugin_ssh.py
Add the option to connect to a server using the domain to make it easier when connecting through the Akamai Zero Trust Client.
make test-unit
Run the following
```linodes-cli ssh -d  label```
> Ssh by domain

- tests/integration/database/test_database.py
Added integration tests for MySQL and PostgreSQL suspend and resume endpoints. Also re-enabled DBaaS tests now that DBaaS V2 is in production.
`make test-int TEST_SUITE=database`
> Added integration tests for suspend and resume

- .github/workflows/e2e-suite.yml
Improving slack test notifications
Overall Test Summary available
Now it is able to thread failures and errors in slack message
e.g.
> Add test summary to slack notification

- linodecli/arg_helpers.py
Improved docstrings for all functions, added static typing for function parameters, and added inline comments in `arg_helpers.py`.
> Improve maintainability of arg_helpers.py

- linodecli/api_request.py
Improved docstrings for all functions, added static typing for function parameters, and added inline comments in `api_request.py`.
The following steps assume you have pulled down this PR locally.
`make test-unit`
`make test-int`
> Improve maintainability of api_request.py

- .github/workflows/e2e-suite.yml
` needs: [integration_tests, process-upload-report]`
The condition above was missed which was causing the summary to be empty during notification job
Tested on forked and private channel 
> Add conditions to notification job in e2e workflow

- .github/workflows/e2e-suite.yml
- pyproject.toml
Deprecation warning is coming from setuptools, on how license variable is defined in pyproject.toml file defines the project.license field. Detailed build warnings below during `make install`:
/private/var/folders/g4/6nz043hs45qbblr441jmsq0c0000gq/T/build-env-ivsf1fb6/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: project.license as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for project.license. You can also use project.license-files.
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See …
> Remove deprecated warning and update license format to latest format

- Makefile
- linodecli/__init__.py
- linodecli/api_request.py
- linodecli/baked/operation.py
- linodecli/cli.py
- linodecli/helpers.py
- tests/unit/test_api_request.py
This pull request updates the `--debug` flag to additionally set the Python `logging` package's log level to `DEBUG`. This allows users to more easily diagnose issues with underlying dependencies (e.g. urllib3) and introduces a standardized logging format we can use for debugging.
This pull request also introduces various log statements to the `linode-cli bake` command, which should make build issues easier to diagnose in CI.
```
make test-unit
```
1. Attempt to re-bake the OpenAPI spec:
```shell
make bake
```
2. Ensure the output contains debug lines similar to the following:
```
DEBUG:linodecli.cli:GET /{apiVersion}/vpcs/{vpcId}/subnets/{vpcSubnetId}: Attempting to generate command for operation …
```
> Configure Python `logging` level when debug flag is specified; add debug logs to bake command

- .gitignore
This pull request drops the `openapi.json` from this repository's tracked files and adds a corresponding entry to the `.gitignore` file
> Add openapi.json to .gitignore; drop from repository

- linodecli/cli.py
- tests/fixtures/cli_test_bake_missing_cmd_ext.yaml
- tests/unit/test_cli.py
This pull request adds logic to raise an error if an OpenAPI path has CLI-enabled actions but does _not_ specify an `x-linode-cli-command` extension. This is necessary because we've recently had OpenAPI specification release candidates make it very far down the pipeline before commands misgrouped under `default` are discovered, which is not intentionally used by any existing commands. 
This pull request also adds a new log entry that occurs when the `x-linode-cli-action` extension is not specified and the operationId is used as a failover.
```
make test-unit
```
> Error on missing x-linode-cli-command extension; log when operationId is used for action

- tests/integration/domains/test_domains_tags.py
- tests/integration/lke/test_lke_enterprise.py
- tests/integration/tags/test_tags.py
Fix 
tests.integration.domains.test_domains_tags
tests.integration.lke.test_lke_enterprise
tests.integration.tags.test_tags
pytest tests/integration/domains/test_domains_tags.py
pytest tests/integration/tags/test_tags.py
pytest tests/integration/lke/test_lke_enterprise.py
make test-int
> fix the failing test for Linode CLI

- tests/integration/lke/test_clusters.py
- tests/integration/lke/test_lke_enterprise.py
```
+ lke tiered-version-view (/{apiVersion}/lke/tiers/{tier}/versions/{version})
+ lke tiered-versions-list (/{apiVersion}/lke/tiers/{tier}/versions)
```
Add integration test coverage for commands above for spec v4.198.0 release
`make test-int TEST_SUITE=lke`
> Add LKE tier integration tests

- linodecli/__init__.py
- linodecli/arg_helpers.py
Renamed `--target-command` to `--alias-command` to address domain test failures.
The following steps assume you have pulled down this PR locally and ran `make install`.
`make test-int TEST_CASE= test_create_domain_srv_record `
`make test-int TEST_CASE= test_list_srv_record `
`make test-int TEST_CASE= test_view_domain_record `
`make test-int TEST_CASE= test_update_domain_record `
`make test-int TEST_CASE= test_delete_a_domain_record `
`make test-int TEST_CASE= test_help_records_list `
Ensure that custom alias functionality introduced in #755 still works by running the following commands:
`linode-cli set-custom-alias --alias-command nodebalancers --alias nbs1`
`linode-cli set-custom-alias --alias nbs2 --alias-command nodebalancers`
`linode-cli remove-custom-alias --alias-command …
> Fixed domain test failures caused by `--target-command` argument

- .github/workflows/release.yml
Migrate to trusted publisher to avoid token usage.
Sample release: https://github.com/zliang-akamai/linode-cli/actions/runs/14677674503/job/41196302382
Do we want to configure [some protection rules for the `pypi-release` environment](https://github.com/linode/linode-cli/settings/environments/6488209563/edit)?
> Trusted publisher for PyPI

- tests/integration/lke/test_lke_enterprise.py
LKE E tier commands have been made available with 4.198.0 spec release with CLI
╰─➤  linode-cli lke tiered-versions-list enterprise                                                                                                                                                                                                                                                                                                                                                                             
╰─➤  linode-cli lke tiered-version-view enterprise "v1.31.1+lke4"
make test-int TEST_SUITE=lke/test_lke_enterprise.py
> Unskip LKE enterprise tier related tests

- linodecli/api_request.py
- linodecli/baked/operation.py
- tests/integration/lke/test_clusters.py
- tests/unit/test_api_request.py
- tests/unit/test_operation.py
This pull request adds support for specifying explicitly empty lists and dicts when a specified in an object argument JSON string. This allows users to reset the labels and taints for an LKE node pool using the `linode-cli lke pool-update` command.
**Syntax for Explicit Empty Dict:**
```bash
linode-cli command action --some-object-arg '{}'
```
**Syntax for Explicit Empty List:**
```bash
linode-cli command action --some-object-arg '[]'
```
```
make test-unit
```
```
make test-int TEST_SUITE=lke/test_clusters.py::test_update_node_pool
```
1. Run the following command to create a new LKE cluster with explicit labels and taints:
```shell
linode-cli lke cluster-create \
--label cli-test \
--region …
```
> Allow specifying explicitly empty dicts and lists for object arguments

- tests/integration/lke/test_clusters.py
Test is made more flexible to check if disk encryption value is set instead of seeing the default value always equal to disabled
`make test-int TEST_CASE=test_create_node_pool_has_disk_encryption_field `
> Update disk encryption node pool test

- tests/integration/cli/test_help.py
- tests/integration/firewalls/test_firewalls.py
- tests/integration/firewalls/test_firewalls_rules.py
- tests/integration/helpers.py
- tests/integration/linodes/helpers_linodes.py
- tests/integration/linodes/test_interfaces.py
- tests/integration/linodes/test_linode_interfaces.py
- tests/integration/nodebalancers/test_node_balancers.py
- tests/integration/obj/test_obj_quota.py
- tests/integration/volumes/test_volumes.py
New API spec 4.199.0 - https://github.com/linode/linode-api-docs/releases/tag/v4.199.0
Add test coverage for following commands:
```
+ firewalls firewall-settings-list (/{apiVersion}/networking/firewalls/settings)
+ firewalls firewall-settings-update (/{apiVersion}/networking/firewalls/settings)
+ firewalls template-view (/{apiVersion}/networking/firewalls/templates/{slug})
+ firewalls templates-list (/{apiVersion}/networking/firewalls/templates)
+ linodes firewalls-update (/{apiVersion}/linode/instances/{linodeId}/firewalls)
+ linodes interface-add (/{apiVersion}/linode/instances/{linodeId}/interfaces)
+ linodes interface-delete (/{apiVersion}/linode/instances/{linodeId}/interfaces/{interfaceId})
+ linodes interface-firewalls-list …
```
> Add and update test coverage for spec v4.199.0

- linodecli/overrides.py
Added override to properly construct tables for DB Engine Config view commands.
Manually run `linode-cli databases mysql-config-view` and `linode-cli databases postgres-config-view` after checking out this PR and building against the proper spec. Confirm that the tables are properly populated and look correct.
> Added override for DB Engine Config view commands

- linodecli/api_request.py
- linodecli/baked/operation.py
- linodecli/baked/request.py
- linodecli/baked/util.py
- linodecli/output/output_handler.py
Fixed the following improperly nested fields in Postgres Database Creation:
```
pg_partman_bgw.interval
pg_partman_bgw.role
pg_stat_monitor.pgsm_enable_query_plan
pg_stat_monitor.pgsm_max_buckets
pg_stat_statements.track
```
The following test steps require that the CLI is build against the latest API spec.
Run the integration test suite to ensure that this fix did not break unrelated functionality:
`make test-int`
Run the following command and ensure that the database is properly created and json is properly printed:
```
linode-cli databases postgresql-create \
--engine postgresql/16 \
--label my-postgres-db \
--region us-east \
--type g6-standard-2 \
--allow_list 172.232.164.239 \
--cluster_size 3 \
--ssl_connection true \
--engine_config.pg.autovacuum_analyze_scale_factor 1 \ …
```
> Fixed improperly nested `engine_config` arguments in Postgres DB creation

- linodecli/plugins/get-kubeconfig.py
Replace usage of `yaml.load` with `yaml.safe_load` in get-kubeconfig plugin.
`make test-unit`
> Fix usage of `yaml.load` in getkubeconfig plugin

- linodecli/__init__.py
- linodecli/api_request.py
- linodecli/arg_helpers.py
- linodecli/cli.py
- tests/integration/cli/test_args.py
- tests/unit/test_api_request.py
This pull request adds a new `--raw-body` argument that can be used to manually specify the body used for a command's API request. This is useful when using fields that aren't yet documented in the OpenAPI specification, or to more easily use the CLI with programmatically generated request bodies. 
```
make test-unit
```
```
make test-int
```
1. Run the following command to create a Linode using a raw request body:
```shell
linode-cli linodes create --raw-body '{"label": "test-linode", "region": "us-mia", "type": "g6-nanode-1"}'
```
2. Ensure the command runs successfully and the Linode is visible in Cloud Manager.
> Add --raw-body argument for POST and PUT requests

- tests/integration/account/test_account.py
- tests/integration/events/test_events.py
- tests/integration/lke/test_lke_enterprise.py
Remove integration tests related to `mark-account-read`, which is deprecated. Also fixed old LKE version causing test to fail.
`make test-int`
> Fix integration tests

- tests/integration/lke/helpers.py
`get_pool_nodesid` was improperly accessing data from `pools-list` causing an error in `test_view_node`
`make test-int TEST_CASE=test_view_node`
> Fixed `get_pool_nodesid` helper

- tests/integration/nodebalancers/fixtures.py
- tests/integration/nodebalancers/test_node_balancers.py
Add Integration test to NodeBalancer with UDP configuration
Test Against Devcloud - api.devcloud.linode.com
make test-int TEST_CASE=test_update_node_balancer_udp_configuration
make test-int TEST_CASE=test_rebuild_node_balancer_udp_configuration
make test-int TEST_CASE=test_list_node_balancer_configurations_with_udp_type
make test-int TEST_CASE=test_view_node_balancer_udp_configuration
make test-int TEST_CASE=test_update_node_for_node_balancer_udp_configuration
make test-int TEST_CASE=test_list_nodes_for_node_balancer_udp_configuration
make test-int TEST_CASE=test_view_node_for_node_balancer_udp_configuration
> Adds integration tests for node balancer with UDP configuration

- tests/integration/database/test_database_engine_config.py
- tests/integration/linodes/test_linodes.py
- tests/integration/nodebalancers/fixtures.py
- tests/integration/nodebalancers/test_node_balancers.py
This pull request addresses various test failures blocking the upcoming Linode CLI release.
CI Test Run: https://github.com/linode/linode-cli/actions/runs/17558540226
The following tests steps assume you have pulled down this PR locally and run `make install`.
```
make test-int
```
> Fix various integration tests (2025-09-08)
