Makefile, README.rst, requirements.txt
Better documentation and better requirements handling should help people
who want to build this from source.  This is to address #34
=> Improved the build experience

Makefile
I see no reason that make install shouldn't be a one-stop shopping experience.
=> fixes issue #34

linodecli/operation.py
Right now this is only for ssl-cert and ssl-key formatted strings to
address the concerns raised in #32.
This can be merged whenever, but won't work until the next version of the OpenAPI specification that includes the formats for the ssl cert and key properties.
=> Added support for pulling input from the filesystem

test/common.bash, test/domains/domain-records.bats, test/domains/master-domains.bats, test/domains/slave-domains.bats, test/test-runner.sh
* Adds initial smoke tests for master/slave domains
* Adds smoke tests for adding/listing/modifying/deleting domain records
cc. @Dorthu
=> ARB-802 - Domains BATS Tests

test/kernels/kernels.bats
*Fair **warning**, running the automated CLI tests will remove all entities on your account. Please update your CLI configuration profile to a test user before running!*
* Added tests for listing and viewing kernels
```bash
bats test/kernels/kernels.bats
./test/test-runner.sh
```
=> Add Kernels BATS tests

README.rst
As Howie and I were talking about the inclusion of new CLI features like k8s-alpha (aww yeah!), he mentioned that people less familiar with python might struggle to upgrade. 
This is proposed language and placement for that upgrade coaching. Suggestions welcome :)
=> add upgrade coaching text for access to new features

linodecli/plugins/k8s-alpha.py
Check if the provided pubkey has a corresponding private key loaded in a running ssh-agent.
=> add: (k8s-alpha) Warn about non-running ssh-agent

test/stackscripts/stackscripts.bats
* Adds tests for creating/updating/deleting stackscripts
* Adds a test for deploying a linode from a stackscript
* Adds negative test for failure to deploy a stackscript to a linode with an incompatible image
=> Add Stackscripts tests

README.rst
@Dorthu and @asauber it might be nice to talk about dependencies before command execution, as per Howie.
=> hint at alpha-k8s dependencies prior to command execution

Dockerfile-bats, test/nodebalancers/nodebalancers.bats
* Remove some faulty  sed params that would backup the original `cli.py` and then do string replacement in the original file. 
* Update assertions for nodebalancers test
=> Bats dockerfile fix

README.rst
=> Update kube readme region default and formatting

test/linodes/linodes.bats, test/linodes/power-status.bats, test/tags/tags.bats
* Does the thing in the title, also adds a test to linodes to create a image-less Linode and assert that it does not boot.
* Updates the tags assertion due to the increase in max length for tags
=> Add Power Status tests, Fix broken tags test

test/common.bash, test/linodes/backups.bats, test/linodes/rebuild.bats, test/linodes/resize.bats, test/stackscripts/stackscripts.bats
* Adds tests for Rebuilding, Resizing, and creating backups.
* Also fixed a breaking stackscripts test
* Also added a helper to create a linode and wait for running
```
brew install bats-core
bats test/linodes/rebuild.bats test/linodes/resize.bats test/linodes/backups.bats
```
=> Add Rebuild, Resize, Backup Tests

test/linodes/backups.bats, test/linodes/resize.bats, test/networking/networking.bats
* Adds some basic smoke tests for the networking command
* This PR was based off the changes in my existing PR, once that is merged I will rebase off master and the changes will be much smaller in scope. For the purposes of this PR, only this is test is up for review:
https://github.com/patthiel/linode-cli/blob/e80e21e2e2cab747b52b6c2c332f4d0bb88dc003/test/networking/networking.bats
=> Add Networking Tests

README.rst, linodecli/__init__.py, linodecli/cli.py, linodecli/configuration.py
Closes #103
This is implemented as described in #103 - feedback is appreciated!
=> Added multi-user support

linodecli/__init__.py
Looks like this was missed in testing #109
=> Fixed plugin invocation with new config system

linodecli/plugins/k8s-alpha.py
=> Check for pubkeys loaded in agent using a much more reliable method

.dockerignore, .gitignore, Dockerfile-bats, test/common.bash, test/domains/domain-records.bats, test/domains/domains-tags.bats, test/linodes/backups.bats, test/linodes/linodes.bats, test/nodebalancers/nodebalancers.bats, test/stackscripts/stackscripts.bats, test/tags/tags.bats, test/test-runner.sh, test/volumes/create-volumes.bats, test/volumes/list-view-update-volumes.bats, test/volumes/resize-volumes.bats
* Updates CLI test assertions for differing API responses across non-production environments.
* Removed some hard coded values in common utility methods
* Updated Volumes assertions for dev/test environments.
* Create temporary files with tags to persist dynamically generated tags across multiple tests
* Updated nodebalancer error messages
* Update domain srv records tests to no longer expect srv records to be in the shape of a bug that was squashed 😄
=> 04-29 CLI Test Maintenance

linodecli/cli.py
Closes #130
Right now, when a new version of the Linode API ships, there is some
span of time where the CLI knows it's out of date, but a new version
isn't available.  After some discussion and thought, this change makes
the CLI check PyPI for a newer version before warning that it should be
upgraded.  This check is only performed when the API response's headers
indicate that a new spec version is available.
Also refactored so that all version checking is disabled if
`--suppress-warnings` is used, since it won't matter in that case.
This adds a single additional HTTP request to CLI calls when the API
indicates a new spec version, which is _probably_ okay.  I'm open to
opinions on this.
I tested this by changing the version the CLI build thought it was, and
the spec version it was built …
=> Only suggest an upgrade when an upgrade exists

scripts/cibuild.sh, scripts/cipublish.sh, scripts/cleanup.sh
* Fixes tag reference. I think. cc @tnation14
=> Fix image tag references

test/common.bash, test/events/events.bats
* Adds tests for events filtering based on entity.id and by event id
=> add: bats tests for event filtering

test/clean-accounts.sh, test/test-runner.sh
* Adds a script that will clean test accounts prior to running the CLI tests and after.
* Updated test runner arg handling to properly check input arguments, regardless of ordering
=> add: clean accounts script

test/volumes/list-view-update-volumes.bats
* Apparently, this test is now throwing a different error.. Not sure if this is due to some spec changes, but this should fix the issue!
=> Fix: volumes test

test/nodebalancers/nodebalancers.bats
* Error output changed slightly, updating this test to reflect the change
=> fix: nodebalancer test error output

linodecli/configuration.py
Closes #140
Due to an oversight, POST and PUT operations would attempt to pull
defaults form the config file even if the CLI was never configured and
we running with the `LINODE_CLI_TOKEN` environment variable defining the
token for it to use.  This could break some automated setups that never
had an interactive tty without using the `--no-defaults` flag, but that
shouldn't be required.
This change tracks if the CLI used an environment-defined token and
skips updating the namespace sent to the operation if the config wasn't
loaded in that case.
=> Don't require a config file when using an environment-defined token

linodecli/operation.py
This fixes tests, and the lke cluster-create operation.
As it happens, the CLI did not parse optional list arguments correctly
(namely, if an optional argument to a list was omitted, the list would
not be created and no items in the list would populate correctly.
Compounding this, objects nested in objects within lists did not
properly restructure after being flattened for the command line.  This
caused nested objects in lists to be sent incorrectly.
Both of the above broke the `linode-cli lke cluster-create` endpoint,
and thereby tests, when `autoscaler` was added to that endpoint, nested
within the `node_pools` object in a list.  This change fixes the issues,
allowing this endpoint to work again.
:warning: I did not write this to handle multiple layers of object
nesting in lists.  I …
=> bug: Fix parsing of nested objects in lists

test/lke/clusters.bats
- Updated --k8s-version in LKE test
- Assert that the new version is returned, too
=> update test lke version

README.rst
I added linode-cli to the Homebrew package manager: Homebrew/homebrew-core#93251
Edited the README to mention that as an installation option.
=> Mention Homebrew installation option in the README

examples/third-party-plugin/example_third_party_plugin.py, examples/third-party-plugin/setup.py, linodecli/__init__.py, linodecli/cli.py, linodecli/configuration.py, linodecli/operation.py, linodecli/output.py, linodecli/plugins/__init__.py, linodecli/plugins/image-upload.py, linodecli/plugins/obj.py, linodecli/plugins/ssh.py, linodecli/response.py, setup.py, version
I ran black, isort, and pycln against the python files
=> File formatting, import cleanup/sorting

README.rst
This pull request adds some README documentation outlining how to specify nested and list arguments.
Resolves #122
=> doc: Add documentation for nested and list arguments

linodecli/plugins/obj.py
If a single part of a multipart upload fails, the whole upload immediately aborts. This PR retries failed parts up to 3 times before aborting.
=> feat: Retry OBJ file part uploads on failure

linodecli/plugins/obj.py
Added a `--chunk-size` option to `obj put` so smaller chunk sizes can be used (reduces the chance of a part upload getting interrupted.)
I also reduced the default chunk size from 5GB to 1GB for the same reason.
TODO:
=> feat: Allowed specifying OBJ upload chunk size

linodecli/configuration.py
This change checks whether the token specified has unrestricted access before attempting to access restricted endpoints during the configuration step.
=> fix: Check for unrestricted access during configuration step

.gitignore, MANIFEST.in, Makefile, setup.py
Changes for release v5.28.0 (API v4.142.0)
=> Release v5.28.0

Makefile, linodecli/__init__.py, linodecli/cli.py, linodecli/completion.py, tests/completion.py
Moving all code related to Shell Completions to its own module and adding unit tests
`make test`
=> moving shell completion to its own module

linodecli/configuration/__init__.py, linodecli/configuration/auth.py, linodecli/configuration/helpers.py, linodecli/configuration/web.py
Refactoring code related to managing the .linode-cli configuration file
Additional refactoring and tests will be done in other PRs to break up the work some
=> refactoring configuration and auth

linodecli/output.py, linodecli/response.py, tests/test_output.py, tests/test_response.py
This pull request refactors and adds unit tests for all output and response-related logic and classes.
```
make test
```
=> new: Refactor and add unit testing to output-related modules

linodecli/plugins/__init__.py, linodecli/plugins/obj.py, tests/test_plugin_obj.py
Type annotations, simplified logics, simplified functions and function calls
=> First Refactoring of obj Plug-In

Makefile, linodecli/__init__.py, linodecli/api_request.py, linodecli/cli.py, linodecli/completion.py, linodecli/configuration/__init__.py, linodecli/configuration/auth.py, linodecli/configuration/helpers.py, linodecli/helpers.py, linodecli/operation.py, linodecli/output.py, linodecli/plugins/firewall-editor.py, linodecli/plugins/image-upload.py, linodecli/plugins/obj.py, linodecli/response.py, pyproject.toml, requirements-dev.txt, tests/completion.py, tests/conftest.py, tests/test_api_request.py, tests/test_cli.py, tests/test_output.py, tests/test_plugin_obj.py, tests/test_response.py
Add `black`, `isort`, and `autofalke` for auto-formatting the code base.
Since this PR formats every file, it will make **conflicts** with the feature branches you are working on. The solution is to add these tools to your branch manually and then let them format the files you are working on. Then creating the PR and accept everything from your feature branch for each conflict.
=> Auto Code Formatter

linodecli/plugins/obj.py
Some functions moved to other place during previous refactoring, so, the function calls in obj plug-in also need an adjustment.
=> Change Func Calls in obj Plug-In to the Newer Functions

linodecli/configuration/__init__.py, linodecli/configuration/helpers.py, linodecli/plugins/obj.py, requirements-dev.txt, setup.py, tests/configuration.py
Refactor all code relevant to generating the linode-cli config file
Add unit tests to the config generation
`make test`
=> ref: refactoring and unit testing config

linodecli/plugins/obj.py
Wrap more logics into functions
install the linode-cli then try commands
`linode-cli obj regenerate-keys` and `linode-cli obj la`
=> Wrap `regenerate_s3_credentials` and `get_credentials `

Makefile, linodecli/__init__.py, linodecli/cli.py, linodecli/configuration/__init__.py, linodecli/configuration/helpers.py
We would need to enforce the code formatters and linters.
`make lint`
=> Check if everything is formatted in `make lint`

tests/integration/conftest.py, tests/integration/helpers.py, tests/integration/test_obj_plugin.py
More tests is always better
`export LINODE_CLI_TOKEN=<YOUR_TOKEN>`
`pytest tests/integration`
=> Improved integration tests for obj plug-in

linodecli/plugins/obj/__init__.py
This is to fix an issue caused by my last PR.
`make testint`
=> Fix `obj ls`

tests/integration/test_obj_plugin.py
More tests, better reliability.
`export LINODE_CLI_TOKEN=<YOUR_TOKEN>`
`make testint`
=> Add update acl test case

linodecli/api_request.py, requirements.txt
This pull request removes the dependency on the deprecated `distutils` version parser.
```
make testunit
```
=> ref: Remove usage of deprecated `distutils` version system

linodecli/cli.py, tests/unit/test_output.py
Added warning when not using `--json` on `linodes ips-list`
=> Added warning when not using `--json` on `linodes ips-list`

tests/integration/conftest.py, tests/integration/fixture_types.py, tests/integration/test_obj_plugin.py
More tests, more reliability.
`export LINODE_CLI_TOKEN=<TOKEN>`
`make testint`
=> Object Storage Website Hosting Integration Test

.github/workflows/pull-request.yml, linodecli/plugins/obj/__init__.py, linodecli/plugins/obj/buckets.py, linodecli/plugins/obj/objects.py
Make them more readable.
`pytest tests/integration/test_obj_plugin.py`
=> Move objects and buckets methods to separate files

MANIFEST.in
relates to #416
---
I have tested out in my local and I can see the requirements.txt is now included
```
...
copying requirements.txt -> linode-cli-5.34.0
...
```
=> release: inc requirements.txt for pypi source tarball file

tests/unit/test_operation.py
Adding unit tests to cover gaps
make testunit
=> Test: add unit test to cover gaps

linodecli/arg_helpers.py, linodecli/helpers.py, linodecli/plugins/obj/__init__.py, tests/integration/helpers.py, tests/integration/obj/test_obj_plugin.py, tests/unit/test_helpers.py
With it the user may get all objects in a bucket now.
I also plan to wrap up all list functionalities in a separated file in the next PR.
You can add more than 1000 files into a bucket and the test the flag.
=> All rows flag for obj plugin

linodecli/plugins/region-table.py, tests/integration/regions/test_plugin_region_table.py
Plugin adding `region-table` command to the CLI.
```bash
lin region-table
```
`make INTEGRATION_TEST_PATH=regions testint`
resolves #492
=> new: adding `region-table` plugin

wiki/Usage.md
Add documentation and example on specifying how objects are differentiated in a list argument.
=> doc: Clarify how list argument differentiates objects

linodecli/baked/colors.py
This change improves the maintainability of colors.py by:
* Adding/updating docstrings
* Implementing static typing on the `colorize_string(...)` method
N/A
=> ref: Improve maintainability of `colors.py` 

linodecli/baked/operation.py
Refactor `baked/operation.py` to improve the readability and maintainability of the file. 
Add docstring to every functions and correct small mistakes in comments.
Run unit test and make sure not breaking the existing logic:
=> ref: Refactor `baked/operation.py`

.github/workflows/e2e-suite.yml, .gitmodules
E2E Test scripts were moved to other GH repo. Hence updating submodule and e2e workflow yaml
Forked Run - https://github.com/ykim-1/linode-cli/actions/runs/10051617255
Test failures not related to this PR
=> test: Update e2e test script submodule repository

tests/integration/helpers.py, tests/integration/lke/test_clusters.py, tests/integration/lke/test_lke_enterprise.py
Adding LKE Enterprise test cases. Note this is only available in `v4beta`
` make MODULE="lke/test_lke_enterprise.py -v" testint`
=> test: Add LKE Enterprise cases

.github/workflows/docker-build.yml, .github/workflows/publish-oci.yml, .github/workflows/publish-pypi.yml, .github/workflows/pull-request.yml, .github/workflows/remote-release-trigger.yml, .github/workflows/unit-tests.yml
This PR upgrades checkout action to V4. 
Some checkout actions were upgraded to v4 and a few were on v3. I have upgraded all the remaining v3 actions to v4.
=> Updating remaining checkout actions to v4

tests/integration/lke/test_clusters.py
The node pool related output is changed because of a recent doc fix. Update the integration test cases to reflect the change. 
```
make MODULE=lke testint
```
https://github.com/linode/linode-cli/actions/runs/12639005395
=> fix: LKE integration test with node pool

tests/integration/image/test_plugin_image_upload.py
Add an assertion to verify `regions` in the output. 
```
make test-int TEST_CASE=test_image_view
```
=> Update image view integration test

linodecli/plugins/obj/__init__.py, linodecli/plugins/obj/objects.py
Updated `boto3` errors in the OBJ plugin to print to stderr instead of stdout.
=> Print OBJ plugin errors to stderr

tests/integration/linodes/test_linodes.py, tests/integration/lke/test_clusters.py
Due the change in Disk Encryption to LA Disk Encryption test were failing
pytest tests/integration/lke/test_clusters.py
pytest tests/integration/linodes/test_linodes.py 
make test-int
=> Update LA Disk Encryption Capability

.github/workflows/e2e-suite-windows.yml, .github/workflows/e2e-suite.yml
This is to cleanup the workflows and rename them to reflect the platform they will run on.
=> Rename workflows; cleanup unnecessary steps

tests/integration/lke/test_lke_enterprise.py
Add helper function to dynamically get K8s version for LKE enterprise for integration tests
`make test-int TEST_SUITE=lke/test_lke_enterprise.py`
=> Add lke versions helper and update tests

tests/integration/database/test_database_engine_config.py, tests/integration/obj/test_obj_quota.py
Add test coverage for Advance DB Config project
`make test-int TEST_SUITE=database/test_database_engine_config.py`
=> Advance DB Config: Add integration test coverage

tests/integration/firewalls/conftest.py, tests/integration/firewalls/test_firewall_settings.py, tests/integration/firewalls/test_firewalls.py, tests/integration/firewalls/test_firewalls_rules.py
Integration test for Firewall related changes 
make test-int TEST_SUITE=firewalls
=> Firewall Integration tests 

linodecli/configuration/config.py, tests/unit/test_configuration.py
Don't custom_aliases is shown as a user
Add a custom_aliases then run `linode-cli show-users`
=> Don't show custom_aliases as a user
